CHANGELOG.md
src/aux-common/Files/FileCalculationContextFactories.ts
src/aux-common/Files/test/FileCalculationContextTests.ts
src/aux-common/Formulas/SandboxInterface.ts
src/aux-common/Formulas/formula-lib.ts

Implementation: Better Query Capabilities

---

.github/workflows/continuous-integration-workflow.yml
CHANGELOG.md
src/aux-common/Files/FilesChannel.ts
src/aux-common/Files/test/FileActionsTests.ts
src/aux-common/Formulas/formula-lib.ts
src/aux-server/aux-web/shared/interaction/DragOperation/BaseFileDragOperation.ts
src/aux-vm-node/vm/VM2Sandbox.spec.ts

When merged, this PR will resolve [YET-5969](https://favro.com/organization/be53ac939ef0ec4b260f4823/0a73c24336ea02e1f6b1f2c5?card=yet-5969) and will fix several issues with building and testing the project on GitHub Actions.

Fix onCombine() argument issue and fix some tests to work on linux

---

CHANGELOG.md
__mocks__/axios.js
__mocks__/os.js
src/aux-server/server/directory/DirectoryClient.spec.ts
src/aux-server/server/directory/DirectoryClient.ts
src/aux-server/server/directory/DirectoryClientSettings.ts
src/aux-server/server/directory/DirectoryEntry.ts
src/aux-server/server/directory/DirectoryService.spec.ts
src/aux-server/server/directory/DirectoryService.ts

- Also switch the key to be based on a generated value instead of a MAC address. (MAC Addresses are too unpredictable)

fix: Use the correct network interfaces for getting private IP Addresses

---

CHANGELOG.md
package-lock.json
package.json
src/aux-common/Files/File.ts
src/aux-common/Files/FileCalculations.ts
src/aux-common/Files/FileEvents.ts
src/aux-common/Files/test/FileActionsTests.ts
src/aux-common/Files/test/FileCalculationContextTests.ts
src/aux-common/Formulas/formula-lib-globals.ts
src/aux-common/Formulas/formula-lib.ts
src/aux-server/aux-web/aux-player/Checkout/Checkout.ts
src/aux-server/aux-web/aux-player/Checkout/Checkout.vue
src/aux-server/aux-web/aux-player/CheckoutForm/CheckoutForm.css
src/aux-server/aux-web/aux-player/CheckoutForm/CheckoutForm.ts
src/aux-server/aux-web/aux-player/CheckoutForm/CheckoutForm.vue
src/aux-server/aux-web/aux-player/CheckoutForm/CheckoutFormGlobals.css
src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
src/aux-server/aux-web/shared/checkout/utils.ts
src/aux-server/aux-web/webpack.dev.js
src/aux-server/package.json
src/aux-server/server/config.dev.ts
src/aux-server/server/config.prod.ts
src/aux-server/server/config.ts
src/aux-server/server/modules/CheckoutModule.spec.ts
src/aux-server/server/modules/CheckoutModule.ts
src/aux-server/server/server.ts
src/aux-vm/test/TestHelpers.ts
src/causal-tree-server-socketio/CausalTreeServerSocketIO.ts

When merged, this PR will add the ability to accept payments via Stripe.
-   Added support for accepting payments via Stripe.
-   To get started with Stripe, first register for an account on [their website](https://dashboard.stripe.com/register).
-   Second, copy your publishable key from the stripe dashboard and add it to the channel's config file in the `stripe.publishableKey` tag.
-   Third, make a new channel. This will be the "processing" channel which will contain all the information actually needed to charge users for payments. And contain the code to actually complete a charge.
-   In this channel, add your Stripe secret key to the config file in the `stripe.secretKey` tag.
-   At this point, you are all setup to accept payments. Use the following functions:
- …

Add the ability to support payments via Stripe

---

CHANGELOG.md
src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.vue

-   Made the background for the menu label gray.

Make the badge on the menu appear gray

---

CHANGELOG.md
src/aux-common/bots/BotCalculations.ts
src/aux-common/bots/BotsChannel.ts
src/aux-common/bots/test/BotActionsTests.ts
src/aux-common/bots/test/BotCalculationContextTests.ts
src/aux-server/aux-web/shared/FormulaHelpers.ts

-   Added the `bot` variable to all functions and formulas.
-   Replacement for `this`.

Add "bot" variable to functions and formulas

---

CHANGELOG.md
src/aux-common/bots/BotCalculations.spec.ts
src/aux-common/bots/BotCalculations.ts
src/aux-server/aux-web/aux-projector/BotTable/BotTable.ts
src/aux-server/aux-web/aux-projector/BotTable/BotTable.vue

-   Showing hidden tags in the bot table will now also show the `shared` tag.

feat: Show the space tag in the bot table when the hidden tags are shown

---

CHANGELOG.md
docs/docs/listen-tags.mdx
src/aux-common/bots/Bot.ts
src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerBotClickOperation.ts
src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
src/aux-server/aux-web/shared/builder/builder.v1.json
src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
src/aux-server/aux-web/shared/interaction/DragOperation/BaseModDragOperation.ts
src/aux-server/aux-web/shared/scene/SceneUtils.ts

-   Added the `face` property to the `@onDrag` and `@onAnyBotDrag` listen arguments.
-   This is the same value that you would get in an `@onClick`.
-   Improved builder to draw a line to the selected bot.
-   Fixed positioning of `#auxLabelAnchor` and `#auxProgressBarAnchor` when the values were set to `left` or `right`.

onDrag listener improvements and other builder improvements

---

CHANGELOG.md
src/aux-server/aux-web/shared/scene/Arrow3D.ts
src/aux-server/aux-web/shared/scene/AuxBot3D.ts
src/aux-server/aux-web/shared/scene/BotRenderer.ts
src/aux-server/aux-web/shared/scene/Game.ts
src/aux-server/aux-web/shared/scene/HtmlMixer.ts
src/aux-server/aux-web/shared/scene/SceneUtils.ts
src/aux-server/aux-web/shared/scene/Text3D.ts
src/aux-server/aux-web/shared/scene/Wall3D.ts
src/aux-server/aux-web/shared/scene/WordBubble3D.ts
src/aux-server/aux-web/shared/scene/WorkspaceMesh.ts
src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/LabelDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/LineToDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/OutlineDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/ProgressBarDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/UserMeshDecorator.ts

-   :rocket: Features
-   Changed the renderer to output colors in the sRGB color space instead of linear.

Change output color space to sRGB instead of linear

---

DEVELOPERS.md
src/aux-server/aux-web/shared/scene/decorators/TextureDecorator.ts

-   Fixed the color encoding of sprites to use sRGB instead of linear.

Fix color space of sprites

---

CHANGELOG.md
docs/docs/components.mdx
docs/docs/tags.mdx
src/aux-server/aux-web/shared/scene/HtmlMixer.ts
src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts

-   Improved the `auxPointable` tag to affect whether iframes are interactable.
-   Fixed an issue with the iframe form where non square scales would not resize the clickable area of the iframe.

iframe fixes and improvements

---

CHANGELOG.md
src/aux-common/aux-format-2/AuxCausalTree2.spec.ts
src/aux-common/aux-format-2/AuxCausalTree2.ts
src/aux-common/aux-format-2/AuxStateHelpers.ts
src/aux-common/aux-format-2/AuxWeaveReducer.ts
src/aux-common/partitions/AuxPartition.ts
src/aux-common/partitions/BotPartition.spec.ts
src/aux-common/partitions/BotPartition.ts
src/aux-common/partitions/CausalRepoPartition.spec.ts
src/aux-common/partitions/CausalRepoPartition.ts
src/aux-common/partitions/MemoryPartition.ts
src/aux-common/partitions/OtherPlayersPartition.spec.ts
src/aux-common/partitions/OtherPlayersPartition.ts
src/aux-common/partitions/ProxyBridgePartition.ts
src/aux-common/partitions/RemoteCausalRepoHistoryPartition.spec.ts
src/aux-common/partitions/RemoteCausalRepoHistoryPartition.ts
src/aux-common/partitions/RemoteCausalRepoPartition.spec.ts
src/aux-common/partitions/RemoteCausalRepoPartition.ts
src/aux-common/partitions/test/PartitionTests.ts
src/aux-server/aux-web/shared/AppManager.ts
src/aux-server/aux-web/shared/vue-components/BotTable/BotTable.ts
src/aux-server/server/modules/SetupChannelModule2.spec.ts
src/aux-vm-browser/partitions/LocalStoragePartition.ts
src/aux-vm-browser/partitions/ProxyClientPartition.ts
src/aux-vm/vm/AuxHelper.spec.ts
src/aux-vm/vm/BaseAuxChannel.spec.ts
src/aux-vm/vm/BaseAuxChannel.ts
src/causal-tree-server/CausalRepoServer.spec.ts
src/causal-tree-server/CausalRepoServer.ts
src/causal-trees/core2/CausalRepo.ts

-   Fixed issues with loading on Servo-based browsers.
-   The issues were mostly related to Servo having not implemented IndexedDB yet.

Servo fixes

---

CHANGELOG.md
docs/docs/actions.mdx
docs/docs/tags.mdx
src/aux-common/bots/Bot.ts
src/aux-common/runtime/AuxLibrary.spec.ts
src/aux-common/runtime/AuxLibrary.ts
src/aux-common/runtime/AuxLibraryDefinitions.def
src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
src/aux-server/aux-web/aux-player/scene/InventorySimulation3D.ts
src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
src/aux-server/aux-web/shared/scene/Input.ts
src/aux-server/aux-web/shared/scene/Physics.ts
src/causal-tree-client-socketio/SocketIOConnectionClient.ts
src/causal-tree-server/CausalRepoServer.spec.ts
src/causal-tree-server/CausalRepoServer.ts
src/causal-tree-server/ConnectionBridge.ts
src/causal-trees/core2/CausalRepoClient.spec.ts
src/causal-trees/core2/CausalRepoClient.ts
src/causal-trees/core2/ConnectionClient.ts
src/causal-trees/core2/MemoryConnectionClient.ts

-   Added several tags to the player bot:
-   These tags are updated by CasualOS and can be used to query the current state of the input system.
-   Camera Tags
-   These tags contain the position and rotation of the player's camera.
-   You can use this to communicate where the player is to other players.
-   `pageCameraPositionX`
-   `pageCameraPositionY`
-   `pageCameraPositionZ`
-   `inventoryCameraPositionX`
-   `inventoryCameraPositionY`
-   `inventoryCameraPositionZ`
-   `pageCameraRotationX`
-   `pageCameraRotationY`
-   `pageCameraRotationZ`
-   `inventoryCameraRotationX`
-   `inventoryCameraRotationY`
-   `inventoryCameraRotationZ`
-   Pointer Tags
-   These tags contain the position and rotation of the player's pointers.
-   You can use this to tell where the VR controllers are …

Add tags to track input states

---

.vscode/launch.json
CHANGELOG.md
docs/docs/actions.mdx
docs/docs/tags.mdx
lerna.json
src/aux-benchmarks/package-lock.json
src/aux-benchmarks/package.json
src/aux-common/bots/Bot.ts
src/aux-common/bots/BotCalculations.ts
src/aux-common/package-lock.json
src/aux-common/package.json
src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
src/aux-server/aux-web/shared/scene/AuxBot3D.ts
src/aux-server/aux-web/shared/scene/DimensionGroup3D.ts
src/aux-server/aux-web/shared/scene/SceneUtils.ts
src/aux-server/aux-web/shared/scene/Text3D.ts
src/aux-server/aux-web/shared/scene/decorators/AuxBot3DDecoratorFactory.ts
src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
src/aux-server/aux-web/shared/scene/decorators/TransformerDecorator.ts
src/aux-server/package-lock.json
src/aux-server/package.json
src/aux-vm-browser/package.json
src/aux-vm-client/package.json
src/aux-vm-deno/package-lock.json
src/aux-vm-deno/package.json
src/aux-vm-node/package.json
src/aux-vm/package.json

-   Added the `transformer` tag.
-   When set to a bot ID, the bot will inherit the position, rotation, and scale of the specified bot inside the page portal.
-   This produces a "parenting" effect that is common in most 3D graphics engines.

Added the transformer tag

---

CHANGELOG.md
src/aux-auth/web/shared/static/acceptable-use-policy.txt
src/aux-auth/web/shared/static/privacy-policy.txt
src/aux-auth/web/shared/static/terms-of-service.txt
src/aux-auth/web/site/AuthAcceptableUsePolicy/AuthAcceptableUsePolicy.vue
src/aux-auth/web/site/AuthPrivacyPolicy/AuthPrivacyPolicy.vue
src/aux-auth/web/site/AuthTerms/AuthTerms.vue
src/aux-server/aux-web/shared/static/acceptable-use-policy
src/aux-server/aux-web/shared/static/acceptable-use-policy.txt
src/aux-server/aux-web/shared/static/privacy-policy
src/aux-server/aux-web/shared/static/privacy-policy.txt
src/aux-server/aux-web/shared/static/terms
src/aux-server/aux-web/shared/static/terms-of-service.txt

-   Updated the Terms of Service, Acceptable Use Policy, and Privacy Policy to make it clearer which websites they apply to.

Update terms, acceptable use policy, and privacy policy

---

CHANGELOG.md
docs/docs/tags.mdx
src/aux-common/bots/Bot.ts
src/aux-common/bots/BotCalculations.ts
src/aux-common/bots/test/BotCalculationContextTests.ts
src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue

chore: Update CHANGELOG, tags.mdx

feat: MenuBot items support formSubtype 'password'

---

docs/docs/tags.mdx
src/aux-server/GettingStarted-aws.md
src/aux-server/GettingStarted-standalone.md
src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
src/aux-server/aux-web/aux-player/themes/dark.scss
src/aux-server/aux-web/aux-player/themes/default.scss
src/aux-server/shared/WebConfig.ts

Add new bios options

---

src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts

Fix iframe scaleY not scaling with scaleX

---

CHANGELOG.md
src/undom/index.ts

Fix an issue where minified builds would cause HTML methods to not work

---

CHANGELOG.md
src/aux-common/bots/BotEvents.ts
src/aux-runtime/runtime/AuxLibrary.spec.ts
src/aux-runtime/runtime/AuxLibrary.ts
src/aux-runtime/runtime/AuxLibraryDefinitions.def
src/aux-vm-browser/managers/AuthCoordinator.spec.ts
src/aux-vm-browser/managers/AuthCoordinator.ts

-   Added the `os.showAccountInfo()` function to show the "Account Information" dialog for users who are logged in.
Closes #343

Implement `os.showAccountInfo()`

---

CHANGELOG.md
src/aux-runtime/runtime/AuxLibrary.spec.ts
src/aux-runtime/runtime/AuxLibrary.ts

Feat/add ArrayBuffer support to bytes.toBase64String and byres.toBase64Url

---

src/aux-server/aux-web/shared/AppManager.ts

-   Added the ability to track some load time metrics using SimpleAnalytics events.
Closes #400

Add the ability to track some load time metrics using SimpleAnalytics events

---

CHANGELOG.md
src/aux-server/aux-web/shared/vue-components/CheckAddressDialog/CheckAddressDialog.ts
src/aux-server/aux-web/shared/vue-components/CheckAddressDialog/CheckAddressDialog.vue
src/aux-server/aux-web/shared/vue-components/EnterAccountInfoDialog/EnterAccountInfoDialog.ts
src/aux-server/aux-web/shared/vue-components/EnterAddressDialog/EnterAddressDialog.ts
src/aux-server/aux-web/shared/vue-components/HasAccountDialog/HasAccountDialog.ts
src/aux-server/aux-web/shared/vue-components/LoginEndpointUI/LoginEndpointUI.ts
src/aux-server/aux-web/shared/vue-components/LoginEndpointUI/LoginEndpointUI.vue
src/aux-server/aux-web/shared/vue-components/LoginUI/LoginUI.ts
src/aux-server/aux-web/shared/vue-components/LoginUI/LoginUI.vue

-   Fixed an issue where custom apps would not reappear after logging in with a code.
Fixes #421

Fix custom apps remaining hidden after login

---

CHANGELOG.md
src/aux-common/bots/StateUpdatedEvent.spec.ts
src/aux-common/bots/StateUpdatedEvent.ts
src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerModDragOperation.ts
src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
src/aux-server/aux-web/shared/interaction/DragOperation/BaseModDragOperation.ts
src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
src/aux-vm-browser/managers/SystemPortalCoordinator.ts

-   Fixed some performance issues when updating lots of bots across multiple frames.

Improve tag update performance

---

CHANGELOG.md
src/aux-common/rpc/GenericRPCInterface.ts
src/aux-records/ServerConfig.ts
src/aux-records/index.ts
src/aux-server/GettingStarted-aws.md
src/aux-server/GettingStarted-standalone.md
src/aux-server/aux-backend/server/config.ts
src/aux-server/aux-backend/shared/ConfigUtils.ts
src/aux-server/aux-backend/shared/Instrumentation.ts
src/aux-server/aux-backend/shared/LoadServer.ts
src/aux-server/aux-backend/shared/ServerBuilder.ts
src/casualos-cli/README.md
src/casualos-cli/cli.ts
src/casualos-cli/schema.ts

-   Improved the [CasualOS CLI](https://www.npmjs.com/package/casualos) to be able to generate and validate server configs.

Add CLI commands for generating and validating server configs

---

CHANGELOG.md
src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.ts

-   Fixed an issue where it was impossible to close the map portal from inside `@onInstJoined`.
Fixes #452

Fix an issue where the map portal would still open if set to `null` inside `@onInstJoined`

---

CHANGELOG.md
src/aux-runtime/runtime/AuxRuntime.spec.ts
src/aux-runtime/runtime/AuxRuntime.ts
src/aux-runtime/runtime/Transpiler.spec.ts
src/aux-runtime/runtime/Transpiler.ts

-   Improved CasualOS to understand and process Typescript class method and property accessibility modifiers correctly.
-   Fixed an issue where library scripts would always error when executing a loop (for, while, etc.).

Fix issues with library scripting

---

CHANGELOG.md
src/aux-server/aux-web/shared/vue-components/BotTable/BotTable.ts

-   Improved the sheetPortal to only create bots in insts that are showing the sheetPortal.
Closes #549

Make the "Create Bot" button in the sheetPortal use the correct inst

---

CHANGELOG.md
src/aux-common/rpc/ErrorCodes.ts
src/aux-records/AuthController.spec.ts
src/aux-records/AuthController.ts
src/aux-records/PrivoClient.ts
src/aux-records/forms/FormError.spec.ts
src/aux-records/forms/FormError.ts
src/aux-server/aux-web/aux-auth/site/OAuthRedirect/OAuthRedirect.ts
src/aux-server/aux-web/aux-auth/site/OAuthRedirect/OAuthRedirect.vue
src/aux-server/aux-web/aux-auth/site/PrivoRegistrationCard/PrivoRegistrationCard.ts

-   Better handle scenarios when an email address is already taken on Privo's side.
Closes #550
Closes #551

Handle some privo errors

---

CHANGELOG.md
src/aux-records/AuthStore.ts
src/aux-records/CachingPolicyStore.ts
src/aux-records/MemoryStore.ts
src/aux-records/PolicyController.spec.ts
src/aux-records/PolicyController.ts
src/aux-records/PolicyStore.ts
src/aux-server/aux-backend/prisma/PrismaPolicyStore.ts

-   Added the `moderator` user role.
-   This will make it much easier for us to moderate content and help ensure that we're creating safe platforms.
Closes #558

Implement the `moderator` user role

---

CHANGELOG.md
src/aux-records/AuthController.ts
src/aux-records/AuthUtils.spec.ts
src/aux-records/AuthUtils.ts
src/aux-records/CryptoUtils.spec.ts
src/aux-records/CryptoUtils.ts
src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
src/aux-server/aux-web/aux-auth/shared/AuthManager.spec.ts
src/aux-server/aux-web/aux-auth/shared/AuthManager.ts
src/aux-server/aux-web/aux-auth/vite.config.mts
src/aux-server/aux-web/aux-player/vite.config.mts
src/casualos-cli/cli.ts

-   Fixed an issue where manually setting a `sessionKey` and `connectionKey` in the URL might not actually log the user in.

Fix issues with non-expiring sessions
