- src/aux-common/Files/test/FileActionsTests.ts
- src/aux-common/Formulas/formula-lib.ts
This PR, when merged, will remove the `event()` function from formula scripts and adds a test to verify that `mod.apply()` can be used to apply a mod onto another mod.
> Remove the event() function from formulas and ensure mods can be applied to mods

- CHANGELOG.md
- src/aux-common/Files/FilesChannel.ts
- src/aux-common/Files/test/FileActionsTests.ts
When merged, this PR will fix the ability to add line comments to the end of scripts. Without this fix, adding a comment to the end of a action script would cause the script to be invalid and therefore not be able to be executed.
> Fix actions to support comments

- CHANGELOG.md
- __mocks__/axios.js
- __mocks__/os.js
- src/aux-server/server/config.dev.ts
- src/aux-server/server/config.prod.ts
- src/aux-server/server/config.ts
- src/aux-server/server/directory/DirectoryClient.spec.ts
- src/aux-server/server/directory/DirectoryClient.ts
- src/aux-server/server/directory/DirectoryClientSettings.ts
- src/aux-server/server/directory/DirectoryService.spec.ts
- src/aux-server/server/directory/DirectoryService.ts
- src/aux-server/server/directory/DirectoryStore.ts
- src/aux-server/server/directory/MemoryDirectoryStore.ts
- src/aux-server/server/directory/MongoDBDirectoryStore.ts
- src/aux-server/server/server.ts
When merged, this PR will add a service that runs in the background which periodically sends basic information to the configured upstream directory.
By default, it is configured to send pings on start and every 5 minutes afterwards.
Here is a list of the information that is sent:
- `key`: The SHA-256 hash of the hostname plus the loopback interface's MAC address.
- `password`: The password that was generated on the device to authenticate to the directory.
- `publicName`: The hostname of the device.
- `privateIpAddress`: The IPv4 Address of the first non-loopback interface sorted by interface name. This is supposed to be the LAN IP that the device has.
> Add the ability to automatically push information to the directory

- CHANGELOG.md
- src/aux-server/server/config.dev.ts
- src/aux-server/server/config.prod.ts
- src/aux-server/server/config.ts
- src/aux-server/server/server.ts
When merged, this PR will allow environment variables to specify which IP Addresses should be trusted as proxies. This allows the `X-Forwarded-For` and `X-Forwarded-Proto` headers to be used in the server which makes the directory function better.
> Add support for specifying Proxy IP Addresses so Express can trust the headers

- CHANGELOG.md
- src/aux-proxy/config.dev.ts
- src/aux-proxy/package.json
- src/aux-proxy/server.ts
- src/aux-proxy/webpack.config.js
- src/aux-server/package.json
- src/aux-server/server/config.dev.ts
- src/aux-server/server/config.prod.ts
- src/aux-server/server/config.ts
- src/aux-server/server/directory/DirectoryClient.spec.ts
- src/aux-server/server/directory/DirectoryClient.ts
- src/aux-server/server/server.ts
- src/tunnel/bin/tunnel.ts
- src/tunnel/index.ts
- src/tunnel/src/TunnelServer.ts
- src/tunnel/src/index.ts
- src/tunnel/src/test/TestClient.ts
- src/tunnel/src/test/index.ts
- src/tunnel/src/websocket/WebSocketClient.ts
- src/tunnel/src/websocket/WebSocketServer.ts
- src/tunnel/src/websocket/index.ts
- src/tunnel/src/websocket/utils.ts
When merged, this PR will add the ability for the directory client to initiate a tunnel connection with an `aux-proxy` server. In effect, this lets AUX servers inside a private network be reachable from outside the network as long as the following is true:
- HTTP and WebSocket requests are made to the proxy. (DNS records point to the proxy server) 
- The first subdomain part matches the key of the directory entry in the following form: `external-{key}`.
- The directory client has an active connection to the server.
> Add support for automatically building a tunnel from a client to a proxy server

- CHANGELOG.md
- src/aux-common/Files/FileCalculations.ts
- src/aux-common/Files/FileEvents.ts
- src/aux-common/Files/test/FileActionsTests.ts
- src/aux-common/Formulas/formula-lib.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-projector/BuilderApp/BuilderApp.ts
- src/aux-server/aux-web/shared/FormulaHelpers.ts
- src/aux-server/aux-web/shared/WebhookUtils.ts
- src/aux-server/server/server.ts
When merged, this PR will add the ability to send and receive HTTP requests on a per-channel basis.
-   Added the ability to send and receive webhooks.
-   Send webhooks using the following functions:
-   `webhook(options)` - options is an object that takes the following properties:
-   `method` - The HTTP Method that should be used for the request.
-   `url` - The URL that the request should be made to.
-   `responseShout` - (Optional) The shout that should happen when a response is received from the server.
-   `headers` - (Optional) The HTTP headers that should be sent with the request.
-   `data` - (Optional) The data that should be sent with the request.
-   `webhook.post(url, data, options)` - Sends a HTTP Post request.
-   `url` - The URL that the request should be made to.
- …
> Add the ability to send and receive webhooks

- CHANGELOG.md
- src/aux-common/Files/File.ts
- src/aux-common/Files/FileCalculations.ts
- src/aux-common/Files/FilesChannel.ts
- src/aux-common/Files/test/FileActionsTests.ts
When merged, this PR will add support for onShout() which gets called whenever a shout or whisper happens.
-   Added the ability to spy on shouts and whispers via the `onShout()` event.
-   `onShout()` is executed on every bot whenever a shout or whisper happens.
-   It is useful for tracking what shouts are being made and modifying responses.
-   Also useful for providing default behaviors.
-   `name` is the name of the action being shouted.
-   `that` is the argument which was provided for the shout.
-   `targets` is an array of bots that the shout was sent to.
-   `listeners` is an array of bots that ran a script for the shout.
-   `responses` is an array of responses that were returned from the listeners.
> Add onShout()

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/aux-player/scene/PlayerSimulation3D.ts
- src/aux-server/aux-web/shared/interaction/CameraControls.ts
- src/aux-server/aux-web/shared/interaction/TweenCameraToOperation.ts
- src/aux-server/aux-web/shared/scene/Game.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
When merged, this PR will add pannable, rotatable, and zoomable options for the camera controls in a context and also add `player.moveTo()` which triggers an instant tween.
-   Added tags to control panning, zooming, and rotating the main camera.
-   `aux.context.pannable`: Controls whether the main camera is able to be panned.
-   `aux.context.zoomable`: Controls whether the main camera is able to be zoomed.
-   `aux.context.rotatable`: Controls whether the main camera is able to be rotated.
-   Added `player.moveTo()` to instantly tween the camera to a bot.
-   In the future, custom tween durations will be supported.
-   Bug Fixes
-   Fixed `player.tweenTo()` to not change the zoom level when it is not specified.
> Add options to limit camera control for contexts and add `player.moveTo()`

- CHANGELOG.md
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotsChannel.ts
- src/aux-common/bots/test/BotActionsTests.ts
-   Renamed `onShout()` to `onAnyListen()`.
-   Added `onListen()` which is an alternative to `onAnyListen()` that is only called on the targeted bots.
> Rename onShout() and add onListen()

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
-   Made the menu item count badge a lighter gray.
> Make the menu badge a lighter gray

- CHANGELOG.md
- package-lock.json
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/shared/public/VueQuagga/Scanner/Scanner.ts
- src/aux-server/aux-web/shared/vue-components/BarcodeScanner/BarcodeScanner.ts
- src/aux-server/aux-web/shared/vue-components/BarcodeScanner/BarcodeScanner.vue
- src/aux-server/package.json
-   Added the ability to choose which camera is used for QR and Barcode scanning.
-   The following functions have been improved:
-   `player.openQRCodeScanner(camera)`
-   `player.openBarcodeScanner(camera)`
-   The `camera` parameter is optional and takes 2 values: `"front"` or `"rear"`.
> Add the ability to choose which camera is used for the QR and Barcode scanners

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/aux-projector/BuilderApp/BuilderApp.ts
- src/aux-server/aux-web/aux-projector/BuilderApp/BuilderApp.vue
- src/aux-server/aux-web/shared/scene/Game.ts
-   Removed several options from the side menu:
-   Removed the channel name from the top of the menu.
-   Removed the login status from the top of the menu.
-   Removed the login/logout options from the menu.
-   The "Logout" option will still be available if you are logged in as a non-guest.
-   Once you are logged out, then the option will dissapear.
-   Removed the "Add Channel" option from the menu in AUXPlayer.
> Cleanup the side menu

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-vm-browser/managers/BotManager.ts
- src/aux-vm/vm/AuxHelper.spec.ts
- src/aux-vm/vm/AuxHelper.ts
-   Added the ability to create temporary bots using the `createTemp()` function.
-   This function behaves exactly the same as `create()` but the created bot is temporary, which means it won't be shared and will be deleted upon refresh.
> Add the ability to create temporary bots

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/server/modules/SetupChannelModule.spec.ts
- src/aux-server/server/modules/SetupChannelModule.ts
- src/aux-server/server/modules/test/TestChannelManager.ts
- src/aux-server/server/server.ts
-   Added the `server.setupChannel(channel, botOrMod)` function.
-   This sends a `setup_channel` action to the server which, if executed using `action.perform()`, will create a channel if it doesn't already exist and place a clone of the given bot or mod in it.
-   Takes 2 parameters:
-   `channel` - The channel that should be created.
-   `botOrMod` - (Optional) The bot or mod that should be cloned and placed inside the new channel. `onCreate()` is triggered after the bot or mod is created so you can use that to script custom setup logic.
-   As mentioned above, you have to receive the `device` action in `onAnyAction()` and do an `action.perform(that.action.event)` to allow channels to be setup via this function.
> Add the `server.setupChannel()` function

- CHANGELOG.md
- src/aux-server/aux-web/aux-projector/BotValue/BotValue.ts
- src/aux-server/aux-web/shared/MonacoHelpers.ts
- src/aux-server/aux-web/shared/interaction/CameraControls.ts
Fixed  [7763](https://favro.com/organization/be53ac939ef0ec4b260f4823/0a73c24336ea02e1f6b1f2c5?card=yet-7763). When calling `player.MoveTo()`, the pan distance was not being updated. Now, the pan distance will correctly be set to the new location. Warning: Moving the camera outside the pan distance will likely lock panning. 
Fixed [7886](https://favro.com/organization/be53ac939ef0ec4b260f4823/0a73c24336ea02e1f6b1f2c5?card=yet-7886). When tag values are set to objects (for instance, with `setTag(this, 'tag', anObject)`), the tag value is now displayed as a JSON.Stringified string rather than `[Object object]`. Warning: editing this text will convert the tag value to a string. You should use the tag value as just a view this way, as text will not be converted to an object.
> Fixed bugs 7886 and 7763 

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotActions.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotsChannel.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/CompletionHelpers.spec.ts
- src/aux-server/aux-web/shared/CompletionHelpers.ts
- src/aux-server/aux-web/shared/FormulaHelpers.ts
- src/aux-server/aux-web/shared/MonacoHelpers.ts
-   Added the `getMod()` function to be able to get all the tags on a bot.
-   Returns a mod containing all the tag values on the bot.
-   The returned mod is always up to date with the bot's current values.
-   Calling `mod.export()` on the returned mod will save the tag code to JSON.
-   For example, if you have a formula `=123`, then `mod.export(getMod(bot))` will return JSON containing `tag: "=123"` instead of `tag: 123`.
-   Added the `tags` variable to all functions and formulas.
-   This is a quick shortcut for `let tags = getMod(bot)` at the beginning of a script/formula.
-   The `tags` variable has some caveats when used in formulas. Namely that the formulas won't be automatically updated when another tag referenced from the formula is updated. (Use `getTag()` for full support)
- …
> Add the "tags" function and formula variable

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib-globals.ts
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotsChannel.ts
- src/aux-common/bots/test/BotActionsTests.ts
-   **Breaking Changes**
-   Changed `create()` and `createTemp()` to automatically set `auxCreator` to the current `this` bot.
-   `create()` no longer takes a bot/bot ID as the first parameter. Instead, you need to use the `from()` function to set the creator ID.
-   e.g. `create(from(bot))`.
> Make create() automatically set auxCreator

- CHANGELOG.md
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/aux-projector/BotTable/BotTable.ts
- src/aux-server/aux-web/aux-projector/BotTable/BotTable.vue
- src/aux-server/aux-web/aux-projector/BotValue/BotValue.ts
- src/aux-server/aux-web/aux-projector/TagEditor/TagEditor.ts
- src/aux-server/aux-web/aux-projector/TagEditor/TagEditor.vue
- src/aux-server/aux-web/shared/vue-components/BotTag/BotTag.css
- src/aux-server/aux-web/shared/vue-components/BotTag/BotTag.ts
- src/aux-server/aux-web/shared/vue-components/BotTag/BotTag.vue
- src/aux-server/aux-web/shared/vue-components/MonacoEditor/MonacoEditorUnscoped.css
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.vue
-   Tags that contain listeners will now display with a @ symbol in front of the tag name.
-   Tags that contain formulas will now diwplay with a = sign after the tag name.
-   Removed the @ symbol from the first line in the code editor when editing a script.
-   Added the ability to use an @ symbol while creating a new tag to prefill the editor with an @.
-   Added the ability to use @ symbols in tags in `getTag()`, `setTag()`, `getBot()`, `getBots()`, `byTag()`, `shout()`, and `whisper()`.
-   Added tag filters for listener tags and formula tags to the bot table.
> Add a bunch of UX improvements for listener and formula tags

- CHANGELOG.md
- src/aux-common/Formulas/Dependencies.spec.ts
- src/aux-common/Formulas/Dependencies.ts
-   Added the ability to detect the `tags` variable in scripts as a reference to tags.
-   This is useful for knowing when to update a formula.
-   Also works with the `raw` variable.
-   Limitations:
-   Does not detect references via the `bot` or `this` variables. (e.g. `bot.tags.abc`)
-   Does not detect references via other bots. (e.g. `otherBot.tags.abc`)
-   Does not detect references if a function is called on the tag. (e.g. `tags.name.toString()`)
-   If you need to work around the limitations, use the `getTag()` function.
> Add the ability to use the tags variable in formulas more reliably

- CHANGELOG.md
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
-   **Breaking Changes**
-   Changed `@onDrop`, `@onDropEnter`, and `@onDropExit` to use the same parameters.
-   `dragBot` - The bot that is being dragged.
-   `to` - an object with the following properties:
-   `context` - The context the bot is being dragged into.
-   `x` - The X grid position the bot is being dragged to.
-   `y` - The Y grid position the bot is being dragged to.
-   `bot` - The bot that the `dragBot` is being dragged onto.
-   `from` - an object with the following properties:
-   `context` The context the bot is being dragged from.
-   `x` - The X grid position the bot is being dragged from.
-   `y` - The Y grid position the bot is being dragged from.
-   `create()` will now automatically set the …
> Update drop event arguments and add additional script features

- CHANGELOG.md
- src/aux-common/bots/BotCalculations.ts
- src/aux-server/aux-web/aux-projector/BotTable/BotTable.ts
- src/aux-server/aux-web/aux-projector/BotTable/BotTable.vue
- src/aux-server/aux-web/aux-projector/BotTagMini/BotTagMini.ts
- src/aux-server/aux-web/aux-projector/BotTagMini/BotTagMini.vue
- src/aux-server/aux-web/aux-projector/MiniBot/MiniBot.ts
- src/aux-server/aux-web/aux-projector/interaction/BuilderInteractionManager.ts
- src/aux-server/aux-web/aux-projector/interaction/ClickOperation/BuilderBotClickOperation.ts
- src/aux-server/aux-web/aux-projector/interaction/ClickOperation/BuilderEmptyClickOperation.ts
- src/aux-server/aux-web/aux-projector/interaction/ClickOperation/BuilderModClickOperation.ts
- src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseClickOperation.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseEmptyClickOperation.ts
-   Showing hidden tags in the bot table will now also show the `shared` tag.
-   Removed the multi-select button from the bot table.
-   Removed the create context button from the bot table.
-   Removed the clear search button from the bot table.
-   Removed the "create mod from selection" button from the bot table.
-   Added the ability to click/tap on a bot preview in the bot table to select a mod of it.
-   Added the ability to drag a bot preview in the bot table to drag a mod of it.
-   Hid the ID tag when a mod is selected.
-   Hid all other buttons when a mod is selected in the bot table.
> Channel Designer sheet updates

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/index.html
-   Added the `player.requestFullscreenMode()` and `player.exitFullscreenMode()` functions.
-   These functions allow jumping in and out of fullscreen, thereby hiding the browser UI controls.
-   Added the `apple-mobile-web-app-*` meta tags to support jumping into fullscreen mode when launching from a bookmark on the iOS home screen.
> Add the ability to jump in and out of fullscreen mode

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/public/three-legacy-gltf-loader/LICENSE
- src/aux-server/aux-web/shared/public/three-legacy-gltf-loader/LegacyGLTFLoader.js
- src/aux-server/aux-web/shared/public/three-legacy-gltf-loader/index.d.ts
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/GLTFHelpers.ts
- src/aux-server/aux-web/shared/scene/PolyUtils.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/debugobjectmanager/DebugObjectManager.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/IMeshDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/OutlineDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/ProgressBarDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/TextureDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/UserMeshDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/WordBubbleDecorator.ts
- src/aux-server/aux-web/webpack.common.js
- src/aux-server/server/server.ts
- src/aux-server/tsconfig.json
-   Added the ability to load GLTF and [poly.google.com](https://poly.google.com) meshes.
-   To load a GLTF model from a URL:
-   Set `#auxForm` to `mesh`.
-   Set `#auxFormSubtype` to `gltf`.
-   Set `#auxFormAddress` to the URL.
-   To load a model from [poly.google.com](https://poly.google.com):
-   Set `#auxForm` to `mesh`.
-   Set `#auxFormSubtype` to `poly`.
-   Set `#auxFormAddress` to the ID of the model.
> Add the ability to load meshes

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/Formulas/Dependencies.spec.ts
- src/aux-common/Formulas/Dependencies.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotActions.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotsChannel.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/FormulaHelpers.ts
- src/aux-vm/managers/DependencyManager.spec.ts
- src/aux-vm/managers/DependencyManager.ts
-   Added the `config`, `configTag`, and `tagName` variables.
-   These variables are useful for creating values and scripts that are shared across multiple bots.
-   The `config` variable is a shortcut for `getBot("#id", tags.auxConfigBot)`.
-   The `tagName` variable is the name of the tag that the script is running in.
-   The `configTag` variable is a shortcut for `config.tags[tagName]`.
> Added support for config bots

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerGrid3D.ts
- src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerBotClickOperation.ts
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
- src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseBotClickOperation.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseClickOperation.ts
- src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
- src/aux-server/aux-web/shared/scene/Input.ts
- src/aux-server/aux-web/shared/scene/debugobjectmanager/DebugObjectManager.ts
- src/aux-server/aux-web/shared/scene/objectpools/CubeHelperPool.ts
- src/aux-server/aux-web/shared/scene/xr/WebXRHelpers.ts
- src/aux-server/aux-web/webpack.common.js
- src/causal-tree-server/CausalRepoServer.ts
- src/causal-trees/core2/CausalRepo.ts
-   When using a controller, dragging a bot with `#auxPositioningMode` set to `absolute` will move it in free space.
-   Additionally, using the grip/squeeze button on the controller while dragging will allow rotating the bot.
> Add the ability to free-drag bots with a VR controller

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/tags.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculationContextFactories.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/aux-player/scene/PlayerPageSimulation3D.ts
-   Improved `@onPlayerPortalChanged` to support `auxLeftWristPortal` and `auxRightWristPortal`.
-   Moved the left and right wrist portals to the top of the wrist instead of the bottom.
-   :book: Documentation
-   Added documentation for the wrist portals and their related config bot tags.
-   Fixed `player.downloadUniverse()` to only include bots from the shared space.
> VR Improvements, Documentation, and a Download Bug Fix

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerModDragOperation.ts
- src/aux-server/aux-web/aux-player/scene/PlayerSimulation3D.ts
- src/aux-server/aux-web/aux-player/scene/PortalConfig.ts
- src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
- src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
- src/aux-server/aux-web/shared/scene/Physics.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
-   Improved drag and drop interactions to calculate intersections with other bots instead of just using grid positioning.
-   This makes it easier drop a bot onto another specific bot.
-   Can be controlled with the `#auxPortalPointerCollisionMode` tag on a portal config.
-   Possible values are:
-   `world` - The mouse pointer collides with other bots in the world when being dragged. (Default)
-   `grid` - The mouse pointer ignores other bots in the world when being dragged.
> Add the ability to collide with other bots when dragging

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/Game.ts
- src/aux-server/aux-web/shared/scene/decorators/AuxBot3DDecoratorFactory.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/LabelDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/ScaleDecorator.ts
- src/causal-tree-server/CausalRepoServer.ts
-   :boom: Breaking Changes
-   Both sprites and iframes now face upwards by default.
-   `#auxAnchorPoint` has been changed to move the bot form inside of its virtual spacing box.
-   Previously, both the virtual box and the bot form was moved to try and preserve the absolute positioning of the bot form when changing anchor points.
-   Now, only the bot form is moved to ensure the correctness of the resulting scale and rotation calculations.
-   `#auxOrientationMode`
-   Renamed the `billboardX` option to `billboardZ`.
-   Changed iframes forms to not support strokes.
-   Added the following options for `#auxAnchorPoint`
-   `centerFront` - Positions the bot form such that the center of the form's front face is at the center of the virtual bot.
-   `centerBack` …
> Fix a bunch of auxAnchorPoint and auxOrientationMode issues

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
-   :boom: Breaking Changes
-   Renamed and removed several `auxAnchorPoint` values.
-   Renamed `centerFront` to `front`.
-   Renamed `centerBack` to `back`.
-   Removed `bottomFront`, `bottomBack`, `topFront`, and `topBack`.
-   Added the ability to specify an array of 3 numbers as the `#auxAnchorPoint` to use a custom offset.
-   Fixed `billboardZ` to rotate with the Y axis of the bot facing upwards.
> auxAnchorPoint cleanup and additional billboarding changes

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.spec.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.spec.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/AuxBot3DDecoratorFactory.ts
- src/aux-server/aux-web/shared/scene/decorators/BotLODDecorator.ts
-   Added LOD triggers based on virtual distance.
-   `@onMaxLODEnter`, `@onMinLODEnter`, `@onMaxLODExit`, `@onMinLODExit` are new listeners that are called when the Max and Min Level-Of-Detail states are entered and exited. There are also "any" versions of these listeners.
-   `bot` - The bot that entered/exited the LOD.
-   `dimension` - The dimension that the LOD was entered/exited in.
-   The `#auxMaxLODThreshold` and `#auxMinLODThreshold` tags can be used to control when the LODs are entered/exited.
-   They are numbers between 0 and 1 representing the percentage of the screen that the bot needs to occupy.
-   The Max LOD is entered when the bot occupies a larger percentage of the screen than the max …
> Add LOD triggers based on virtual distance

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.md
- DEVELOPERS.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotsChannel.ts
- src/aux-common/bots/test/BotActionsTests.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerEmptyClickOperation.ts
- src/aux-server/aux-web/shared/AppManager.ts
- src/aux-server/aux-web/shared/DownloadHelpers.ts
- src/aux-server/aux-web/shared/interaction/CameraControls.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseEmptyClickOperation.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.spec.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotLODDecorator.ts
- src/aux-server/aux-web/shared/vue-components/UploadFiles/UploadFiles.css
- src/aux-server/aux-web/shared/vue-components/UploadFiles/UploadFiles.ts
- src/aux-server/aux-web/shared/vue-components/UploadFiles/UploadFiles.vue
- src/aux-server/server/modules/WebhooksModule2.spec.ts
-   Added the ability to modify tags directly on bots in `that`/`data` values in listeners.
-   Allows doing `that.bot.tags.abc = 123` instead of `setTag(that.bot, "abc", 123)`.
-   Added the `@onGridUp` and `@onGridDown` listeners.
-   `dimension` - The dimension that the grid was clicked in.
-   `position` - The X and Y position that was clicked.
-   Changed the Level-Of-Detail calculations to use the apparent size of a bot instead of its on-screen size.
-   Apparent size is the size the bot would appear if it was fully on screen.
-   Under the new system, the LOD of a that is on screen bot will only change due to zooming the camera. Bots that are fully off screen will always have the minimum LOD.
-   Added …
> Improve LODs, add onGridUp/Down, onFileUpload, and additional script improvements

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerModDragOperation.ts
- src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
- src/aux-server/aux-web/aux-player/scene/InventorySimulation3D.ts
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/aux-player/scene/PlayerPageSimulation3D.ts
- src/aux-server/aux-web/aux-player/scene/PortalConfig.ts
- src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
- src/aux-server/aux-web/shared/interaction/CameraControls.ts
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/GameObject.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
- src/aux-server/aux-web/shared/scene/Text3D.ts
- src/aux-server/aux-web/shared/scene/decorators/BotLODDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
-   Added the `#auxPointable` tag to determine whether a bot can interact with pointers.
-   Defaults to `true`.
-   When `false`, the bot won't be clickable or hoverable and will not receive drop events.
-   Depending on the `#auxPositioningMode` it is still possible to stack bots on top of it though.
-   Added the `@onFocusEnter`, `@onFocusExit`, `@onAnyFocusEnter` and `@onAnyFocusExit` listen tags.
-   These are triggered when a bot is directly in the center of the screen.
-   Uses the `#auxFocusable` tag to determine whether a bot is focusable.
-   `dimension` - The dimension that the the bot was (un)focused in.
-   `bot` - The bot that was (un)focused.
-   Added the `nothing` aux form.
-   Does exactly …
> Added focus events, the nothing form, auxPointable, and LOD and panning fixes

- CHANGELOG.md
- src/aux-common/aux-format-2/AuxCausalTree2.spec.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.css
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.vue
- src/aux-vm/DebugHelpers.ts
- src/aux-vm/vm/BaseAuxChannel.ts
- src/causal-trees/core2/Atom2.spec.ts
- src/causal-trees/core2/Atom2.ts
- src/causal-trees/core2/Weave2.spec.ts
- src/causal-trees/core2/__snapshots__/Atom2.spec.ts.snap
-   Added a button on the sheet code editor to show errors that the script has run into.
-   It is very basic at the moment. There are no line/column numbers, no timestamps, and no way to clear the errors.
-   Errors are automatically pulled from error space and queried based on the following tags:
-   `auxError` must be `true`
-   `auxErrorBot` must be the ID of the bot whose script is in the editor.
-   `auxErrorTag` must be the name of the tag that is being edited.
-   The following tags are displayed for each error:
-   `auxErrorName` is the name of the error that occurred.
-   `auxErrorMessage` is the message that the error contained.
-   Fixed the color encoding of sprites to use sRGB instead of linear.
-   Fixed an issue where atoms …
> Add a way to display errors from scripts

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/tags.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-common/partitions/BotClient.ts
- src/aux-common/partitions/BotPartition.spec.ts
- src/aux-common/partitions/BotPartition.ts
- src/aux-common/partitions/MemoryBotClient.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/AuxBot3DDecorator.ts
- src/aux-server/aux-web/shared/scene/AuxBotVisualizer.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
- src/aux-server/server/mongodb/MongoDBBotStore.ts
- src/aux-server/server/servers/BotHttpServer.ts
- src/aux-server/server/storage/BotStore.ts
- src/aux-server/shared/ClearBotsRequest.ts
- src/aux-vm-client/partitions/BotHttpClient.ts
- src/aux-vm/vm/AuxHelper.spec.ts
- src/aux-vm/vm/AuxHelper.ts
-   :boom: Breaking Changes
-   Renamed the `billboardZ` auxOrientationMode option to `billboardTop`.
-   Added the `server.loadErrors(bot, tag)` function to make loading error bots from the error space easy.
-   `bot` is the bot or bot ID that the errors should be loaded for.
-   `tag` is the tag that the errors should be loaded for.
-   Added the `server.destroyErrors()` function to clear all the errors in the universe.
-   Added the `billboardFront` auxOrientationMode option to billboard the front of a bot instead of its top.
-   Added the ability to set `auxFormAnimation` to an array.
-   When set, the list of animations will play in sequence.
-   The last animation will loop forever until changed.
-   Added the `experiment.localFormAnimation(bot, animation)` …
> Add API functions for errors, add billboardFront, and add the ability to sequence animations

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.css
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
-   Improved the `player.showInputForTag()` modal.
-   Removed the "Save" and "Cancel" buttons. The tag will be saved automatically.
-   Hid the modal title when none is provided in the options.
-   Made the text box in the modal auto-focus.
-   Made the show/hide animations happen quicker.
> Improved the player.showInputForTag() modal

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxCompiler.spec.ts
- src/aux-common/runtime/AuxCompiler.ts
- src/aux-common/runtime/AuxGlobalContext.spec.ts
- src/aux-common/runtime/AuxGlobalContext.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.css
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.css
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.ts
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.vue
-   Added the `player.showInput(value, options)` function.
-   Shows an input modal but without requiring a bot and a tag.
-   Returns a [Promise](https://web.dev/promises/) that resolves with the final value when the input modal is closed.
-   The function accepts two arguments:
-   `value` is a string containing the value that should
-   `options` is an object that takes the same properties that the options for `player.showInputForTag()` takes.
-   Added the ability to use the [`await` keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) in scripts.
-   `await` tells the system to wait for a promise to finish before continuing.
-   This makes it easier to write scripts which deal with tasks that take a while to complete.
> Add the player.showInput() function

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/Formulas/formula-lib.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
-   Added the `player.share(options)` function.
-   This will trigger the device's social share capabilities to share the given URL or text.
-   Note that this only works on Android and iOS phones and only works in response to some user action like a click.
-   `options` is an object with at least one of the following properties:
-   `url` - The URL to share. (optional)
-   `text` - The text to share. (optional)
-   `title` - The title of the document that is being shared. (optional)
> Add the player.share() function

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/aux-player/ItemDimension.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.css
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue
- src/aux-server/aux-web/shared/scene/Text3D.ts
- src/aux-server/aux-web/shared/scene/decorators/LabelDecorator.ts
-   :boom: Breaking Changes
-   The default label alignment for bots in the page portal has changed from `center` to `left`. It is now consistent across all portals.
-   Added the `auxLabelAlignment` tag.
-   Possible values are:
-   `center` - Aligns the text in the center of the label.
-   `left` - Aligns the text to the left of the label.  (default)
-   `right` - Aligns the text to the right of the label.
> Add the auxLabelAlignment tag

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/components.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/BotEvents.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.spec.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.ts
- src/aux-common/runtime/AuxGlobalContext.spec.ts
- src/aux-common/runtime/AuxGlobalContext.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.ts
- src/aux-vm-node/modules/AdminModule2.ts
- src/aux-vm/vm/AuxHelper.ts
- src/causal-tree-server/CausalRepoServer.spec.ts
- src/causal-tree-server/CausalRepoServer.ts
- src/causal-tree-server/DeviceManagerHelpers.spec.ts
- src/causal-tree-server/DeviceManagerHelpers.ts
- src/causal-trees/core/Event.ts
- src/causal-trees/core2/CausalRepoClient.spec.ts
- src/causal-trees/core2/CausalRepoClient.ts
- src/causal-trees/core2/CausalRepoEvents.ts
- src/causal-trees/core2/CausalRepoSession.ts
-   Added the `server.storyPlayerCount()` function.
-   Returns a promise that resolves with the number of players currently connected to the current story.
-   Optionally accepts a parameter which indicates the story to check.
-   Added the `server.totalPlayerCount()` function.
-   Returns a promise that resolves with the total number of players connected to the server.
-   Added the `server.stories()` function.
-   Returns a promise that resolves with the list of stories that are on the server.
-   Removed the globals bot tags from the documentation since they no longer exist.
> Add functions to allow requesting metadata from the server

- CHANGELOG.md
- src/aux-common/partitions/OtherPlayersPartition.spec.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.spec.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.ts
- src/aux-server/server/server.ts
- src/aux-vm-node/managers/AuxCausalRepoManager.spec.ts
- src/aux-vm-node/managers/AuxCausalRepoManager.ts
- src/causal-tree-cli/migrate/mongodb.ts
- src/causal-tree-server/CausalRepoServer.spec.ts
- src/causal-tree-server/CausalRepoServer.ts
- src/causal-tree-store-mongodb/MongoDBRepoStore.ts
- src/causal-trees/core2/CausalRepoEvents.ts
- src/causal-trees/core2/CausalRepoObject.ts
- src/causal-trees/core2/CausalRepoStore.ts
- src/causal-trees/core2/MemoryCausalRepoStore.ts
- src/causal-trees/core2/test/CausalRepoStoreTests.ts
-   Added a reflog and sitelog for stories so that it is possible to track the history of a story branch and which sites have connected to it.
-   This will make it easier for us to recover from data loss issues in the future since we'll be able to lookup data like the last commit that a branch pointed at or which atoms were added to a branch.
> Add more ways to recover lost data

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/JitsiMeet.ts
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/JitsiMeet.vue
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/LICENSE
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/README.md
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.css
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.vue
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortalConfig.ts
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.css
- src/aux-server/aux-web/shared/vue-components/ShowInputModal/ShowInputModal.vue
- src/aux-vm-browser/partitions/LocalStoragePartition.ts
-   Added the `meetPortal`.
-   This is a special portal that, instead of loading bots, loads a [Jitsi Meet](https://meet.jit.si/) meeting with the given room code.
-   All rooms are publicly accessible (but not searchable), so longer room codes will be more private.
-   You can use the `meetPortalConfigBot` option to reference the bot that should be used to configure the meet portal.
-   The following options are available:
-   `meetPortalVisible` - Whether the meet portal should be visible. This allows you to be joined to a meet while keeping your screen on the page portal. (Defaults to true)
-   `meetPortalAnchorPoint` - The anchor point that the meet portal should use. Possible options are:
-   `fullscreen` - The meet portal should take the entire screen. …
> Add the ability to start and join Jitsi Meet meetings

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-common/partitions/OtherPlayersPartition.spec.ts
- src/aux-common/partitions/OtherPlayersPartition.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.spec.ts
- src/aux-common/partitions/RemoteCausalRepoPartition.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.css
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/scene/decorators/LineToDecorator.ts
- src/aux-server/aux-web/shared/vue-components/BaseGameView.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.css
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.vue
- src/causal-tree-server/CausalRepoServer.spec.ts
- src/causal-tree-server/CausalRepoServer.ts
- src/causal-tree-server/DeviceManagerHelpers.ts
- src/causal-trees/core/Event.ts
-   Improved how the meet portal, page portal, and sheet portal work together to make space for each other.
-   Added the `left` and `right` options for `meetPortalAnchorPoint`.
-   Changed the `top` and `bottom` options for `meetPortalAnchorPoint` to occupy half of the screen.
-   Added the `server.players()` function to get the list of player IDs that are connected to the current story.
-   Returns a promise that resolves with the list of player IDs.
-   Added the `remoteWhisper(players, name, arg)` function to make sending messages to other players easy.
-   Takes the following arguments:
-   `players` is the player ID or list of player IDs that should receive the shout.
-   `name` is the name of the message.
-   `arg` is the data that should be included.
- …
> Improve the meet portal positioning and add remote shouts/whispers

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- package-lock.json
- package.json
- src/aux-common/bots/Bot.ts
- src/aux-server/package.json
- src/aux-server/server/server.ts
- src/aux-vm-browser/vm/AuxVMImpl.ts
- src/aux-vm-node/vm/AuxVMNode.ts
- src/aux-vm/managers/BotHelper.ts
- src/aux-vm/vm/AuxChannel.ts
- src/aux-vm/vm/AuxVM.ts
- src/aux-vm/vm/BaseAuxChannel.spec.ts
- src/aux-vm/vm/BaseAuxChannel.ts
- src/aux-vm/vm/test/TestAuxVM.ts
-   Added the ability to respond to webhooks by returning data from `@onWebhook`.
-   If the returned value is a string, then it will be used for the response.
-   If the returned value is an object, then it should have the following properties:
-   `data` - The value that should be used as the body of the response.
-   `headers` - An object that contains the HTTP headers that should be set on the response. (Optional)
-   `status` - The numerical status code that should be set on the response. (Optional) If omitted, status code 200 will be used.
-   Added the `dataPortal`.
-   This is a special portal that only works on web requests and must be specified in the URL.
-   Setting it to a Bot ID will return the JSON of the bot with the given ID.
-   Setting it to a …
> Add the ability to return data from webhooks and use data portals

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/partitions/MemoryPartition.ts
- src/aux-common/partitions/test/PartitionTests.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
-   Added the `@onBotAdded` and `@onAnyBotsAdded` listen tags.
-   These are triggered whenever a bot is added to the local story.
-   Note that this is different from `@onCreate` because you will be notified whenever a bot is added to the state even if it has already been created.
-   An example of this are bots in the `otherPlayers` space. You cannot create bots in this space but you will be notified via `@onBotAdded` and `@onAnyBotsAdded`.
-   `@onBotAdded` is triggered on the bot that was added. There is no `that`.
-   `@onAnyBotsAdded` is triggered on every bot whenever one or more bots are added.
-   `bots` - The array of bots that were added.
-   Added the `@onAnyBotsRemoved` listen tags.
-   These are …
> Add listen tags for when bots are added, removed, and changed

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/scene/GameAudio.ts
- src/causal-tree-server/CausalRepoServer.spec.ts
- src/causal-tree-server/CausalRepoServer.ts
- src/causal-tree-store-mongodb/MongoDBRepoStore.ts
-   Improved `player.playSound(url)` to return a promise that resolves with a sound ID.
-   This sound ID can be used with `player.cancelSound(soundID)` to stop the sound from playing.
-   Added the `player.bufferSound(url)` and `player.cancelSound(soundID)` functions.
-   `player.bufferSound(url)` can be used to pre-load a sound so that there will be no delay when using `player.playSound()`.
-   Returns a promise that resolves once the sound has been loaded.
-   `player.cancelSound(soundID)` can be used to stop a sound that is already playing.
-   Returns a promise that resolves once the sound has been canceled.
> Add the player.bufferSound() and player.cancelSound() functions

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
-   Changed `@onListen` to only be sent to bots which have a listener for the shout/whisper.
-   Previously `@onListen` would be sent to all bots that were targeted by the shout/whisper.
-   Changed `shout()` and `whisper()` to cost 1 energy point.
-   This helps prevent infinite loops.
-   The energy point is only deducted if a bot has a listener for the event.
-   Fixed an issue where `onBotAdded`, `onAnyBotsAdded`, `onAnyBotsRemoved`, `onBotChanged`, and `onAnyBotsChanged` would reset the energy counter.
> Fixes and improvements for infinite loops

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
-   Changed `experiment.localPositionTween()` and `experiment.localRotationTween()` to take different arguments and return a promise.
-   the 4th parameter is now an options object instead of the easing options.
-   This options object is able to accept easing and duration values.
-   Additionally the functions now return promises.
-   See the docs for examples.
-   Fixed an issue where `experiment.localPositionTween()` and `experiment.localRotationTween()` may not execute if triggered during `@onCreate()`.
> Tween Improvements

- CHANGELOG.md
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.spec.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
- src/aux-server/README.md
- src/aux-server/aux-web/shared/vue-components/BotID/BotID.ts
- src/aux-server/aux-web/shared/vue-components/BotID/BotID.vue
- src/aux-server/aux-web/shared/vue-components/BotSheet/BotSheet.ts
- src/aux-server/aux-web/shared/vue-components/BotSheet/BotSheet.vue
- src/aux-server/aux-web/shared/vue-components/BotSheet/SheetPortalConfig.ts
- src/aux-server/aux-web/shared/vue-components/BotTable/BotTable.ts
- src/aux-server/aux-web/shared/vue-components/BotTable/BotTable.vue
- src/aux-server/aux-web/shared/vue-components/BotValue/BotValue.css
- src/aux-server/server/config.dev.ts
- src/aux-server/server/config.prod.ts
- src/aux-server/server/config.ts
- src/aux-server/server/server.ts
- src/aux-vm-browser/managers/BotPanelManager.ts
- src/aux-vm-deno/vm/DenoVM.ts
- src/aux-vm/managers/BotHelper.spec.ts
- src/aux-vm/managers/BotHelper.ts
- src/aux-vm/vm/AuxConfig.ts
- src/aux-vm/vm/test/TestAuxVM.ts
-   Renamed the `_editingBot` tag to `editingBot`.
-   sheetPortal Improvements
-   Added the `@onSheetTagClick` listener which is triggered when a tag name is clicked.
-   Added the `@onSheetBotIDClick` listener which is triggered when a Bot ID is clicked.
-   Added the `@onSheetBotClick` listener which is triggered when a bot visualization is clicked in the sheet.
-   Added the `sheetPortalShowButton` config bot tag to control whether the button in the bottom right corner of the sheet is shown.
-   Added the `sheetPortalButtonIcon` config bot tag to control the icon on the button in the bottom right corner of the sheet.
-   Added the `sheetPortalButtonHint` config bot tag to control the tooltip on the button in the bottom right corner of the sheet.
-   Added the `sheetPortalAllowedTags` …
> Sheet Portal Improvements

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculationContext.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/runtime/AuxGlobalContext.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-common/runtime/CompiledBot.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
- src/aux-common/runtime/Utils.ts
- src/aux-common/runtime/test/TestScriptBotFactory.ts
-   Added the `experiment.getAnchorPointPosition()` and `math.getAnchorPointOffset()` functions.
-   These are useful for determining where a bot would be placed if it had a particular anchor point.
-   See the [docs](https://docs.casualsimulation.com/docs/actions) for more info.
> Add the experiment.getAnchorPointPosition() and math.getAnchorPointOffset() functions

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.css
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.vue
- src/aux-server/aux-web/aux-player/PlayerUtils.ts
- src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
- src/aux-server/aux-web/shared/scene/Input.ts
- src/aux-server/aux-web/shared/vue-components/PieProgress/PieProgress.css
- src/aux-server/aux-web/shared/vue-components/PieProgress/PieProgress.ts
- src/aux-server/aux-web/shared/vue-components/PieProgress/PieProgress.vue
-   Improved bots in the menu portal to support additional tags.
-   Added the ability to change the height of menu items by using `scale` and `scaleY`.
-   Added the ability to set an icon for a menu item by using the `formAddress` tag.
-   Added the ability to set arbitrary CSS styles on a menu bot by using the `menuItemStyle` tag.
-   This lets you use margins and borders to indicate grouping.
-   Added the ability to show a pie-chart progress bar on a menu item by using the `progressBar` tags.
-   Added the ability to use `@onPointerUp` and `@onPointerDown` for menu.
> Menu improvements

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
- src/aux-common/runtime/RuntimeStateVersion.ts
- src/aux-common/runtime/index.ts
- src/aux-common/runtime/test/TestScriptBotFactory.ts
- src/aux-vm-browser/vm/AuxVMImpl.ts
- src/aux-vm-deno/vm/DenoVM.ts
- src/aux-vm-node/vm/AuxVMNode.ts
- src/aux-vm/managers/BotWatcher.ts
- src/aux-vm/vm/AuxChannel.ts
- src/aux-vm/vm/AuxVM.ts
- src/aux-vm/vm/BaseAuxChannel.spec.ts
- src/aux-vm/vm/BaseAuxChannel.ts
- src/aux-vm/vm/test/TestAuxVM.ts
-   Added the `insertTagText()`, `deleteTagText()`, `insertTagMaskText()`, and `deleteTagMaskText()` functions to allow scripts to work with multi-user text editing.
-   `insertTagText(bot, tag, index, text)` inserts the given text at the index into the given tag on the given bot.
-   `insertTagMaskText(bot, tag, index, text, space?)` inserts the given text at the index into the tag and bot. Optionally accepts the space of the tag mask.
-   `deleteTagText(bot, tag, index, deleteCount)` deletes the given number of characters at the index from the tag and bot.
-   `deleteTagMaskText(bot, tag, index, deleteCount, space?)` deletes the given number of characters at the index from the tag and bot. Optionally accepts the space of the tag mask.
> Add the insertTagText(), deleteTagText(), insertTagMaskText(), and deleteTagMaskText() functions

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
- src/aux-server/aux-web/shared/vue-components/TagPortal/TagPortal.ts
- src/aux-server/aux-web/shared/vue-components/TagPortal/TagPortal.vue
-   Added the ability to use the `transformer` tag on the player bot to parent the player to a bot.
-   Added the ability to edit tag masks in the tag portal by setting the `tagPortalSpace` tag on the player bot.
> Improve the transformer tag and tag portal

- CHANGELOG.md
- src/aux-common/partitions/MemoryPartition.spec.ts
- src/aux-common/partitions/MemoryPartition.ts
- src/aux-server/aux-web/shared/MonacoHelpers.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-vm-browser/partitions/LocalStoragePartition.spec.ts
- src/aux-vm-browser/partitions/LocalStoragePartition.ts
- src/aux-vm/vm/BaseAuxChannel.spec.ts
- src/causal-trees/core2/CausalTree2.ts
-   Added the ability to use the `color` tag on GLTF meshes to apply a color tint to the mesh.
-   Fixed an issue that prevented deleting the first character of a script/formula in the multi-line editor.
-   Fixed an issue where tag edits on bots in the tempLocal and local spaces would be applied to the multi-line editor twice.
> Editing Fixes and GLTF Improvements

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.md
- DEVELOPERS.md
- Dockerfile
- Dockerfile.arm32
- Jenkinsfile
- package-lock.json
- src/aux-common/package.json
- src/aux-common/runtime/AuxCompiler.spec.ts
- src/aux-common/runtime/AuxCompiler.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-common/runtime/Transpiler.spec.ts
- src/aux-custom-portals/bin/common.js
- src/aux-vm/vm/AuxHelper.ts
-   Improved handling of errors so they have correct line and column numbers in their stack traces.
-   Currently, this only functions correctly on Chrome-based browsers (Chrome, Edge, Opera, etc.). Part of this is due to differences between how web browsers generate stack traces and part is due to what browsers support for dynamically generated functions.
> Better Stack Traces

- CHANGELOG.md
- DEVELOPERS.md
- docs/docs/actions.mdx
- package-lock.json
- src/aux-common/bots/BotEvents.ts
- src/aux-common/package.json
- src/aux-common/runtime/AuxCompiler.spec.ts
- src/aux-common/runtime/AuxCompiler.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/Transpiler.spec.ts
- src/aux-common/runtime/Transpiler.ts
- src/aux-common/runtime/__snapshots__/AuxLibrary.spec.ts.snap
- src/aux-common/runtime/__snapshots__/AuxRuntime.spec.ts.snap
- src/aux-common/yjs/YjsHelpers.spec.ts
- src/aux-common/yjs/YjsHelpers.ts
- src/aux-custom-portals/bin/common.js
- src/aux-server/aux-web/shared/MonacoHelpers.ts
- src/aux-server/aux-web/shared/public/monaco-jsx-highlighter/MonacoJSXHighlighter.css
- src/aux-server/aux-web/shared/public/monaco-jsx-highlighter/MonacoJSXHighlighter.ts
- src/aux-server/aux-web/shared/vue-components/HtmlAppContainer/HtmlAppContainer.ts
- src/aux-server/package.json
- src/aux-server/typings/jscodeshift.d.ts
- src/aux-vm-browser/package.json
- src/aux-vm/portals/HtmlAppBackend.spec.ts
- src/aux-vm/portals/HtmlAppBackend.ts
- src/aux-vm/portals/__snapshots__/HtmlAppBackend.spec.ts.snap
-   Added the ability to use [JSX](https://reactjs.org/docs/introducing-jsx.html) for Apps instead of the `html` string helper.
-   JSX allows you to use a HTML-like language directly inside listeners. This provides some nice benefits including proper syntax highlighting and error messages.
-   For example:
```javascript
let result = <h1>Hello, World!</h1>;
```
-   Due to convienience this will probably become the preferred way to write HTML for apps, however the `html` string helper will still be available.
> JSX Support

- CHANGELOG.md
- docs/docs/tags.mdx
- jest.config.js
- package-lock.json
- src/aux-server/aux-web/shared/scene/Arrow3D.ts
- src/aux-server/aux-web/shared/scene/ArrowHelper.ts
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/LineSegments.ts
- src/aux-server/aux-web/shared/scene/MeshUtils.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/LineToDecorator.ts
- src/aux-server/aux-web/shared/scene/objectpools/CubeHelperPool.ts
- src/aux-server/package.json
- src/aux-server/typings/three.meshline.d.ts
-   `lineStyle` now defaults to `line` instead of `arrow`.
-   Improved `lineTo` and `strokeColor` to use lines that support custom widths.
> Improve lines to support custom widths

- CHANGELOG.md
- src/aux-common/bots/Bot.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
-   Added the `links` variable as a shortcut for `thisBot.links`.
-   Added `bot.vars` and `os.vars` as an easy way to store and lookup variables by name.
-   `os.vars` works exactly the same as `globalThis`.
-   `bot.vars` allows you to store special values in a bot that cannot be stored in either `bot.tags` or `bot.masks`.
-   Added the ability to whisper to a bot by using `bot.listener()` instead of `whisper(bot, "listener")`.
-   e.g.
```typescript
let result = thisBot.myScript(argument);
```
is equivalent to
```typescript
let [result] = whisper(thisBot, 'myScript', argument);
```
-   Added the ability to shout to bots by using `shout.listener()` instead of `shout("listener")`.
-   e.g.
```typescript
let results = shout.myScript(argument);
```
is equivalent to
```typescript
let …
```
> Scripting improvements

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/scene/Game.ts
-   Added the `os.arSupported()` and `os.vrSupported()` functions to query device support for AR and VR respectively. Both of these are promises and must be awaited.
```typescript
const arSupported = await os.arSupported();
if (arSupported) {
//...
}
const vrSupported = await os.vrSupported();
if (vrSupported) {
//...
}
```
-   Added shouts for entering and exiting AR and VR:
-   `@onEnterAR` - Called when AR has been enabled.
-   `@onExitAR` - Called when AR has been disabled.
-   `@onEnterVR` - Called when VR has been enabled.
-   `@onExitVR` - Called when VR has been disabled.
> AR and VR scripting improvements.

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- docs/docs/variables.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/JitsiMeet.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.vue
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortalConfig.ts
-   Added shouts for loading and leaving the meet portal:
-   `@onMeetLoaded` - Called when the user has finished loading the meet portal.
-   `@onMeetLeave` - Called when the user leaves the meet portal.
-   Added the `os.meetCommand(command, ...args)` function that sends commands directly to the Jitsi Meet API. Supported commands can be found in the [Jitsi Meet Handbook](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#commands).
-   Added the following meet portal configuration tags. These must be set on the `meetPortalBot`:
-   `meetPortalPrejoinEnabled` - Whether the meet portal should have the prejoin screen enabled.
-   The prejoin screen is where the user can setup their display name, microphone, camera, and other settings, before actually joining the meet.
- …
> Expanded meetPortal scripting.

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-web/shared/MonacoHelpers.ts
- src/aux-server/aux-web/shared/MonacoUtils.ts
- src/aux-server/aux-web/shared/vue-components/MonacoEditor/MonacoEditor.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.vue
- src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.css
- src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.ts
- src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.vue
- src/aux-server/aux-web/shared/vue-components/TagValueEditor/TagValueEditor.ts
- src/aux-server/aux-web/shared/vue-components/TagValueEditor/TagValueEditor.vue
- src/aux-vm-browser/managers/SystemPortalManager.spec.ts
- src/aux-vm-browser/managers/SystemPortalManager.ts
-   Added global search to the systemPortal.
-   Useful for finding a word or phrase in the tags of all the bots in an inst.
-   For example, you can find all the places where a shout occurrs by typing "shout" into the search box.
-   Can be accessed by using `Ctrl+Shift+F` while the systemPortal is open or by selecting the eyeglass icon on the left side of the screen.
> Feature: global search

- CHANGELOG.md
- docs/docs/actions.mdx
- package-lock.json
- package.json
- src/aux-common/bots/BotCalculations.spec.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/package.json
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-common/runtime/RuntimeBot.spec.ts
- src/aux-common/runtime/RuntimeBot.ts
- src/aux-common/runtime/Utils.spec.ts
- src/aux-common/runtime/Utils.ts
- src/aux-common/runtime/test/TestScriptBotFactory.ts
- src/aux-server/aux-web/shared/vue-components/BotTable/BotTable.ts
- src/aux-server/aux-web/shared/vue-components/BotTag/BotTag.css
- src/aux-server/aux-web/shared/vue-components/BotTag/BotTag.vue
-   Added the ability to store dates in tags by prefixing them with `📅`.
-   Dates must be formatted similarly to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601):
-   `2012-02-06` (year-month-day in UTC-0 time zone)
-   `2015-08-16T08:45:00` (year-month-day + hour:minute:second in UTC-0 time zone)
-   `2015-08-16T08:45:00 America/New_York` (year-month-day + hour:minute:second in specified time zone)
-   `2015-08-16T08:45:00 local` (year-month-day + hour:minute:second + in local time zone)
-   In scripts, date tags are automatically parsed and converted to DateTime objects.
-   DateTime objects are easy-to-use representations of date and time with respect to a specific time zone.
-   They work better than the built-in [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Referen …
> Better date time support

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/release.yml
- CHANGELOG.md
- src/aux-auth/README.md
- src/aux-auth/shared/AuthMetadata.ts
- src/aux-auth/web/iframe/AuthHandler.ts
- src/aux-auth/web/shared/AuthManager.ts
- src/aux-auth/web/site/AuthHome/AuthHome.ts
- src/aux-auth/web/site/AuthHome/AuthHome.vue
- src/aux-auth/web/vite.config.ts
- src/aux-server/aux-web/shared/vue-components/RecordsUI/RecordsUI.css
- src/aux-server/aux-web/shared/vue-components/RecordsUI/RecordsUI.ts
- src/aux-server/aux-web/shared/vue-components/RecordsUI/RecordsUI.vue
- src/aux-server/aux-web/shared/vue-components/RecordsUI/RecordsUIGlobal.css
- src/aux-vm-browser/managers/AuthHelper.ts
- src/aux-vm/auth/AuxAuth.ts
- src/aux-vm/managers/AuthHelperInterface.ts
- src/aux-vm/managers/RecordsManager.spec.ts
-   Added the ability to login with a phone number instead of an email address.
-   This feature is enabled by the `ENABLE_SMS_AUTHENTICATION` environment variable during builds.
> Add the ability to login to the Auth site with SMS

- CHANGELOG.md
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.spec.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
- src/aux-server/aux-web/shared/vue-components/MonacoTagEditor/MonacoTagEditor.ts
-   Added the ability to force AUX to intepret values as strings by prefixing the tag value with the 📝 emoji.
-   This can be useful for when you want to ensure that a tag value is interpreted a string.
-   For example, the string `"01"` will be interpreted as the number `1` by default but `"📝01"` will preserve the leading 0.
> Add the string tag prefix for tag values

- CHANGELOG.md
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.spec.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/runtime/AuxRuntime.spec.ts
- src/aux-common/runtime/AuxRuntime.ts
-   Added the ability to force a tag to interpret values as numbers by prefixing the tag value with the 🔢 emoji.
-   This can be useful when you want to ensure that a tag is interpreted as a number.
-   Added support for scientific notation in numbers.
-   `1.23e3` will now be interpreted as `1230`.
-   Fixed an issue where `infinity` and `-infinity` would always be calculated as `NaN` instead of their corresponding numerical values.
> Add the number emoji prefix for tag values

- CHANGELOG.md
- docs/docs/actions.mdx
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/interaction/DragOperation/PlayerBotDragOperation.ts
- src/aux-server/aux-web/aux-player/scene/MapPortalGrid3D.ts
- src/aux-server/aux-web/aux-player/scene/PlayerSimulation3D.ts
- src/aux-server/aux-web/shared/interaction/DragOperation/BaseBotDragOperation.ts
- src/aux-server/aux-web/shared/interaction/DragOperation/SnapInterface.ts
- src/aux-server/aux-web/shared/scene/BoundedGrid3D.ts
- src/aux-server/aux-web/shared/scene/CompoundGrid3D.ts
- src/aux-server/aux-web/shared/scene/Grid3D.ts
- src/aux-server/aux-web/shared/scene/PriorityGrid3D.spec.ts
- src/aux-server/aux-web/shared/scene/PriorityGrid3D.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
-   Added the `os.addDropGrid(...grids)` and `os.addBotDropGrid(botId, ...grids)` functions to make it easy to snap bots to a custom grid.
-   These functions are useful if you want to snap bots to a grid with a custom position or rotation.
-   Additionally, they can be used to move bots in a grid that is attached to a portal bot.
-   See the documentation for detailed usage information.
> Add the os.addDropGrid() and os.addBotDropGrid() functions

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/glossary/DataRecord.mdx
- docs/docs/glossary/FileRecord.mdx
- docs/docs/glossary/ManualApprovalDataRecord.mdx
- src/aux-auth/web/iframe/AuthHandler.ts
- src/aux-auth/web/shared/AuthManager.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/shared/vue-components/BotChat/BotChat.ts
- src/aux-server/aux-web/shared/vue-components/RecordsUI/RecordsUI.ts
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
- src/aux-vm-browser/managers/AuthHelper.ts
- src/aux-vm-browser/managers/BotManager.ts
- src/aux-vm-browser/managers/index.ts
- src/aux-vm/auth/AuxAuth.ts
- src/aux-vm/managers/AuthHelperInterface.ts
- src/aux-vm/managers/RecordsManager.spec.ts
- src/aux-vm/managers/RecordsManager.ts
-   Added the ability to specify which auth site records should be loaded/retrieved from.
-   This is useful for saving or getting records from another CasualOS instance.
-   The following functions have been updated to support an optional `endpoint` parameter:
-   `os.recordData(key, address, data, endpoint?)`
-   `os.getData(recordName, address, endpoint?)`
-   `os.listData(recordName, startingAddress?, endpoint?)`
-   `os.eraseData(key, address, endpoint?)`
-   `os.recordManualApprovalData(key, address, data, endpoint?)`
-   `os.getManualApprovalData(recordName, address, endpoint?)`
-   `os.listManualApprovalData(recordName, startingAddress?, endpoint?)`
-   `os.eraseManualApprovalData(key, address, endpoint?)`
-   `os.recordFile(key, data, options?, endpoint?)`
-   `os.eraseFile(key, …
> Add the ability to support querying separate records instances

- CHANGELOG.md
- __mocks__/@casual-simulation/three/examples/jsm/lines/Line2.js
- __mocks__/@casual-simulation/three/examples/jsm/lines/LineGeometry.js
- __mocks__/@casual-simulation/three/examples/jsm/lines/LineMaterial.js
- jest.config.js
- package-lock.json
- package.json
- src/aux-common/package.json
- src/aux-common/tsconfig.json
- src/aux-components/package.json
- src/aux-server/aux-web/shared/scene/Arrow3D.ts
- src/aux-server/aux-web/shared/scene/ArrowHelper.ts
- src/aux-server/aux-web/shared/scene/LineSegments.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
- src/aux-server/package.json
- src/aux-server/typings/casual-simulation.three.d.ts
- src/causal-tree-cli/debug/index.ts
- src/causal-tree-cli/package.json
- src/causal-tree-cli/tsconfig.json
- tsconfig.test.json
-   Improved how lines are rendered to use an implementation built into three.js.
-   This makes bot strokes that are scaled appear correct.
-   This change also makes lines and strokes appear the same size on screen no matter the zoom level of the camera. This can make it easier to identify bots when zoomed out a lot.
> Use Three.js Line2 for lines and strokes

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/JitsiMeet.ts
- src/aux-server/aux-web/shared/vue-components/JitsiMeet/JitsiTypes.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.ts
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortal.vue
- src/aux-server/aux-web/shared/vue-components/MeetPortal/MeetPortalConfig.ts
-   Added the `os.meetFunction(functionName, ...args)` function to allow querying the current meet portal meeting state.
-   `functionName` is the name of the function that should be triggered from the [Jitsi Meet API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe/#functions).
-   `args` is the list of arguments that should be provided to the function.
-   Returns a promise that resolves with the result of the function call.
-   Added the `@onMeetEntered` and `@onMeetExited` shouts which are triggered whenever the current user starts/stops participating in a meet.
-   Unlike `@onMeetLoaded`, `@onMeetEntered` is only triggered after the user clicks the "Join" button from the meeting waiting room.
-   See the documentation for more detailed information.
-   Added the …
> Added os.meetFunction(), @onMeetEntered, @onMeetExited, and meetPortalJWT

- .husky/pre-commit
- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/glossary/DataRecord.mdx
- docs/docs/glossary/ManualApprovalDataRecord.mdx
- package-lock.json
- package.json
- src/aux-auth/server/MongoDBDataRecordsStore.ts
- src/aux-auth/server/index.ts
- src/aux-auth/serverless/aws/src/handlers/RecordsV2.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-records-aws/DynamoDBDataStore.spec.ts
- src/aux-records-aws/DynamoDBDataStore.ts
- src/aux-records/DataRecordsController.spec.ts
- src/aux-records/DataRecordsController.ts
- src/aux-records/DataRecordsStore.spec.ts
- src/aux-records/DataRecordsStore.ts
- src/aux-records/Errors.ts
- src/aux-records/MemoryDataRecordsStore.ts
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
- src/aux-vm/managers/AuthHelperInterface.ts
- src/aux-vm/managers/RecordsManager.spec.ts
- src/aux-vm/managers/RecordsManager.ts
-   Added the ability to specify an options object with `os.recordData(key, address, data, options)` that can specify update and delete policies for the data.
-   These policies can be useful to restrict the set of users that can manipulate the recorded data.
-   `options` is an object with the following properties:
```typescript
let options: {
/**
* The HTTP Endpoint that should be queried.
*/
endpoint?: string;
/**
* The policy that should be used for updating the record.
* - true indicates that the value can be updated by anyone.
* - An array of strings indicates the list of user IDs that are allowed to update the data.
*/
updatePolicy?: true | string[];
/**
* The policy that should be used for deleting the record.
* - true indicates that the value can be erased by anyone.
* - An array …
```
> Implement Update/Delete Policies for Data Records

- CHANGELOG.md
- docs/docs/actions.mdx
- docs/docs/listen-tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotEvents.ts
- src/aux-common/runtime/AuxLibrary.spec.ts
- src/aux-common/runtime/AuxLibrary.ts
- src/aux-common/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/scene/AnimationHelper.ts
- src/aux-server/aux-web/shared/scene/Simulation3D.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
-   Added the `os.startFormAnimation(bot, animationName, options?)`, `os.stopFormAnimation(bot, options?)`, `os.listFormAnimations(botOrAddress)`, and `os.bufferFormAddressGLTF(address)` functions.
-   `os.startFormAnimation(bot, animationName, options?)` is used to trigger an animation on the given bot. Returns a promise that resolves when the animation has started. It accepts the following parameters:
-   `bot` - The bot or list of bots that the animation should be triggered on.
-   `animationName` - The name or index of the animation that should be started.
-   `options` - The additional parameters that should be used for the animation. Optional. It should be an object with the following properties:
-   `startTime` - The time that the animation should start playing. It should be the …
> Better animation controls

- CHANGELOG.md
- DEVELOPERS.md
- src/aux-server/aux-web/shared/scene/Game.ts
Fixed an issue where `os.getMediaPermission` would leave tracks in a MediaStream running. Some browsers/devices release these automatically, while others would leave the tracks running and cause issues with other systems that utilize audio and video hardware like augmented reality.
> Media permission track release

- CHANGELOG.md
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
This PR adds support for the `color` tag on all meshes and materials of a bot loading a glTF model. Previously CasualOS would only apply the `color` tag value to the first mesh child of glTF. This PR also fixes material texture registration and disposal for glTF models that have many materials and textures.
Before:
After:
> Mesh glTF form fixes - Color & Disposal

- CHANGELOG.md
- src/aux-server/aux-web/shared/scene/AuxBot3D.ts
- src/aux-server/aux-web/shared/scene/DimensionGroup3D.ts
- src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts
This PR fixes an issue with bots being transformed by other bots not updating their bounding objects (bounding box, bounding sphere, etc). This was the cause for the bug reported in Issue #276 
The `DimensionPositionDecorator` simply keeps track of the world position of its transformer (if it has one). If the transformer changes world position then the `DimensionPositionDecorator` will update the bounding objects of the transformed bot.
Before: 
After:
> Transformed bot bounding objects fix

- CHANGELOG.md
- docs/docs/tags.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
This PR adds support for a new `formOpacity` tag. 
The `formOpacity` tag is used as a modifier on  the default opacity value of all materials on a bot shape.
This allows bot shapes to be semi-transparent. 
- A `formOpacity` value of `1` means that the bot's mesh materials are effectively in their default opacity and transparency state.
- A `formOpacity` value `< 1` means that the bot's mesh materials become transparent and that the `formOpacity` value is used to modify each material's default opacity level.
- A `formOpacity` value of `0` would make the bot invisible.
`formOpacity` is implemented for all mesh and material based bot shapes, including custom glTF models and the keyboard.
> Added formOpacity tag to support semi-transparent bots.

- CHANGELOG.md
- src/aux-server/aux-web/shared/AudioRecorder.ts
This PR fixes a bug with `os.beginAudioRecording` when set to `stream: true` and a `mimeType` of anything other than `audio/x-raw`. 
Previously `MediaAudioRecorder` was providing empty `Blob` data to `@onAudioChunk` when running the `MediaAudioRecorder` with `stream: true` and an audio encoding format (ie `mimeType: 'audio/webm'`). The fix is to provide the buffer rate to the recorder's `start()` function which accepts a `timeslice` argument. When `timeslice` is provided, the recorder's `dataavailable` event gets triggered properly and `@onAudioChunk` gets the `Blob` chunks as originally intended. 
Another alteration included in this PR is to await the `finalBlobPromise` before invoking `dataAvailable.complete()`. This gives the recorder time to stop and call its final `dataavailable` …
> Fixed MediaAudioRecorder when set to stream mode.

- docs/docs/tags.mdx
- playwright/gridPortal.spec.ts
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
The "skybox" term can be changed. I had researched any possible trademark issues and it seems clear to use.
The premise of "skybox" is to invert the normals on a typical 3js sphere allowing for images to map the interior of a sphere.
Practical uses (most common) can be found in WebXR implementations.
> feat: Add skybox option to form tag

- CHANGELOG.md
- src/aux-server/GettingStarted-aws.md
- src/aux-server/GettingStarted-standalone.md
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-server/aux-web/shared/AppManager.ts
- src/aux-vm-browser/vm/AuxVMImpl.ts
- src/aux-vm-browser/vm/AuxVMUtils.spec.ts
- src/aux-vm-browser/vm/AuxVMUtils.ts
When merged, this PR will allow the `VM_ORIGIN` environment variable to be configured to isolate insts from each other and from the frontend.
e.g. Setting `VM_ORIGIN` to `https://{{inst}}.example.com` will cause a static inst `myInst` to use the HTTP origin `https://myInst.example.com`, which causes it to be isolated from `myOtherInst` which would use the HTTP origin `https://myOtherInst.example.com`.
This change is backwards-compatible, meaning that static insts which already exist on a device should not be affected.
Fixes #367
> Add the ability to isolate insts from each other by using separate domains

- CHANGELOG.md
- src/aux-vm/portals/HtmlAppBackend.ts
-   Fixed an issue where `os.unregisterApp()` would not trigger Preact cleanup code.
Fixes #311
> Make `os.unregisterApp()` trigger Preact hooks cleanup code

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/MenuPortal.ts
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-vm/managers/SimulationManager.ts
-   Fixed an issue where `os.unloadInst()` would not work when going from 2 instances to 1 instance.
-   Fixed an issue where menuPortal items would remain even if their inst was unloaded.
Fixes #361 
Fixes #378
> Fix `os.unloadInst()`

- CHANGELOG.md
- src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
-   Fixed an issue where it was possible to have multiple login attempts at once by calling `os.requestAuthBot()` multiple times without waiting for one to complete.
Fixes #345
> Prevent the login system from getting stuck with multiple login attempts

- CHANGELOG.md
- src/aux-records/MemoryRateLimiter.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-server/aux-backend/server/server.ts
- src/aux-server/aux-backend/serverless/aws/src/LoadServer.ts
- src/aux-server/aux-backend/shared/ServerBuilder.ts
-   Added the ability to track rate limits for the WebSocket API separately from the HTTP API.
-   The `websocketRateLimit` property on the `SERVER_CONFIG` controls the websockets rate limits. If not specified, then the options from `rateLimit` will be used for websockets and HTTP.
-   Additionally, the `websocketRateLimitPrefix` in `redis` controls the namespace that values are stored at in Redis. If not specified, then the `rateLimitPrefix` will be used for both.
Closes #352
> Add the ability to control WebSocket rate limits separately from HTTP rate limits

- CHANGELOG.md
- src/aux-common/bots/BotEvents.ts
- src/aux-runtime/runtime/AuxLibrary.spec.ts
- src/aux-runtime/runtime/AuxLibrary.ts
- src/aux-runtime/runtime/AuxLibraryDefinitions.def
- src/aux-vm/managers/RecordsManager.spec.ts
- src/aux-vm/managers/RecordsManager.ts
-   Added the `os.getRecordsEndpoint()` function to get the default records endpoint.
-   Records actions, like `os.recordData()`, `os.getData()`, `os.recordFile()`, etc. can be passed an endpoint which specifies which backend should be used for the request.
-   If no endpoint is specified, then a default is used.
-   `os.getRecordsEndpoint()` returns a promise that resolves to the endpoint that is used by default.
Closes #342
> Implement `os.getRecordsEndpoint()`

- CHANGELOG.md
- src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
- src/aux-server/aux-backend/prisma/PrismaAuthStore.ts
- src/aux-server/aux-backend/server/server.ts
-   Support case-insensitive matching of email address when logging in.
-   Previous versions would create separate accounts for email addresses that differed only in case.
-   Now, if an exact match is not found, a case-insensitive search will be made for users when attempting to login by email.
-   This will prevent cases where a user gets a new account because they mistakenly changed the case of their email address.
-   Technically, email addresses are supposed to be case-sensitive, but pretty much every email server treats them as case-insensitive.
Closes #330
> Implement case-insensitive matching for email addresses

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
-   Fixed an issue where `os.calculateRayFromCamera()` would return incorrect results for the ray origin.
> Fix `os.calculateRayFromCamera()`

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
-   Fixed an issue where the `miniMapPortal` and `miniGridPortal` were not able to be resized.
Fixes #409
> Fix `miniGridPortal` and `miniMapPortal` resizing

- CHANGELOG.md
- src/aux-runtime/runtime/AuxLibrary.spec.ts
- src/aux-runtime/runtime/AuxLibrary.ts
-   Fixed an issue where `os.getCurrentInst()` would return `undefined` if the inst is a static inst.
Fixes #415
> Make `os.getCurrentInst()` work for static insts

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-server/aux-web/aux-player/UrlUtils.spec.ts
- src/aux-server/aux-web/aux-player/UrlUtils.ts
- src/aux-server/aux-web/shared/AppManager.ts
- src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.ts
- src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.vue
-   Fixed an issue where setting `?owner=player` in the URL while not being logged in would cause a public inst to be loaded instead of prompting the user to login.
Fixes #418
> Prompt the user for login when attempting to load a player owned inst

- CHANGELOG.md
- src/aux-server/aux-backend/shared/ServerBuilder.ts
-   Added the ability to specify separate Redis servers for websocket connections, inst data, caches, and rate limits.
Closes #423
> Add the ability to support separate Redis servers

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.css
- src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerEmptyClickOperation.ts
- src/aux-vm/managers/SimulationManager.ts
-   CasualOS will now send `@onGridClick`, `@onGridUp`, and `@onGridDown` shouts to all loaded insts.
-   Fixed an issue where it was possible for CasualOS to waste resources by loading the portals for an inst multiple times.
-   Fixed an issue where the miniGridPortal slider bar would interfere with the menuPortal.
Closes #425
> Support `@onGridClick`, `@onGridUp`, and `@onGridDown` for all loaded insts

- CHANGELOG.md
- src/aux-common/rpc/ErrorCodes.spec.ts
- src/aux-common/rpc/ErrorCodes.ts
- src/aux-records/AuthController.spec.ts
- src/aux-records/AuthController.ts
- src/aux-records/AuthStore.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-server/aux-backend/prisma/PrismaAuthStore.ts
- src/aux-server/aux-backend/schemas/auth.prisma
- src/aux-server/aux-backend/schemas/migrations/20240402170012_allow_marking_sessions_as_revocable/migration.sql
-   Added the ability to create accounts that are not associated with an email or phone number.
-   These accounts are also issued a session key that cannot be revoked and does not expire.
-   They will mostly be used for one-time subscriptions and machine users.
Closes #432
> Add the ability to create custom user accounts 

- CHANGELOG.md
- jakefile.js
- package.json
- pnpm-lock.yaml
- src/aux-common/rpc/GenericRPCInterface.spec.ts
- src/aux-common/rpc/GenericRPCInterface.ts
- src/aux-records/RecordsClient.spec.ts
- src/aux-records/RecordsClient.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
- src/casualos-cli/.gitignore
- src/casualos-cli/LICENSE.txt
- src/casualos-cli/README.md
- src/casualos-cli/cli.ts
- src/casualos-cli/index.ts
- src/casualos-cli/package.json
- src/casualos-cli/schema.ts
- src/casualos-cli/script/build-cli.mjs
- src/casualos-cli/script/clean.mjs
- src/casualos-cli/script/cli-configs.mjs
- src/casualos-cli/script/dev-cli.mjs
- src/casualos-cli/tsconfig.json
- tsconfig.json
-   Added a command line interface (CLI) for CasualOS.
-   It is available on NPM as `casualos`, and provides functionality to query the CasualOS backend API.
-   It currently provides the following operations:
-   `login` - Authenticates the cilent to a CasualOS backend.
-   `query` - Queries a CasualOS backend.
-   `repl` - A Read-eval-print-loop (REPL) that makes interacting with the CasualOS backend via JavaScript really easy.
> Add a command line interface for CasualOS

- src/aux-common/rpc/GenericRPCInterface.ts
- src/aux-records/AuthController.spec.ts
- src/aux-records/AuthController.ts
- src/aux-records/AuthStore.ts
- src/aux-records/AuthUtils.spec.ts
- src/aux-records/AuthUtils.ts
- src/aux-records/RecordsController.spec.ts
- src/aux-records/RecordsController.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-records/SubscriptionController.spec.ts
- src/aux-records/SubscriptionController.ts
- src/aux-records/TestUtils.ts
- src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
- src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
- src/aux-server/aux-backend/prisma/PrismaAuthStore.ts
- src/aux-server/aux-backend/schemas/auth.prisma
- src/aux-server/aux-backend/schemas/migrations/20240408180450_add_user_roles/migration.sql
-   Added the `superUser` user role.
-   This is internal to CasualOS and is not related to roles that control access to record data.
-   There are currently only two roles: `none`, and `superUser`.
-   Currently, roles have to be assigned manually through the database. There is not API to grant a user the `superUser` role.
-   All users default to the `none` role.
-   When assigned the `superUser` role, a user has access to some operations that they would not normally have access to, including:
-   `getUserInfo` for all users
-   `createAccount`
-   `listSessions` for all users
-   `listRecords` for all users and studios
-   `listStudios` for all users
-   `listStudioMembers` for all studios
-   `getSubscriptions` for all users and studios
- Made the `createAccount` procedure only allow …
> Add the `superUser` role

- CHANGELOG.md
- src/aux-records/AuthController.spec.ts
- src/aux-records/AuthController.ts
- src/aux-records/AuthStore.ts
- src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
- src/aux-server/aux-web/aux-auth/shared/AuthManager.ts
- src/aux-server/aux-web/aux-auth/site/index.ts
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-server/aux-web/shared/AppManager.ts
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
- src/aux-vm-browser/managers/AuthHelper.ts
-   Added the ability to specify user login details in the URL.
-   When logged in, CasualOS stores a `sessionKey` and a `connectionKey` in the local storage of their web browser to keep them logged in.
-   When the `sessionKey` and `connectionKey` query params are specified in the URL, they will be used instead of the stored ones.
-   Additionally, they work for users who are not logged in.
-   This makes it possible to give someone a URL that grants them automatic access to an account.
Closes #440
> Support specifying a `sessionKey` in the URL

- CHANGELOG.md
- src/aux-records/AuthStore.ts
- src/aux-records/MemoryStore.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-records/SubscriptionConfiguration.spec.ts
- src/aux-records/SubscriptionConfiguration.ts
- src/aux-records/SubscriptionController.spec.ts
- src/aux-records/SubscriptionController.ts
- src/aux-records/Utils.spec.ts
- src/aux-records/Utils.ts
- src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
- src/aux-server/aux-backend/prisma/PrismaAuthStore.ts
-   Added the `updateSubscription` operation (`POST /api/v2/subscriptions/update`) to allow super users to grant a subscription to users or studios.
-   Currently, it can only be used to grant/revoke simple non-stripe subscriptions. If the user already has a stripe subscription, then the function will refuse to make changes.
> Add the ability to manually assign subscriptions to users

- CHANGELOG.md
- src/aux-vm/portals/HtmlAppBackend.ts
-   Exposed the following properties from `HTMLVideoElement`:
-   `currentTime`
-   `ended`
-   `paused`
-   `muted`
-   `volume`
-   `playbackRate`
-   Note that these properties are only updated when an event is received from the element. (e.g. `currentTime` will be exposed if you are listening to `onTimeUpdate`)
Closes #456
> Expose several properties from `HTMLVideoElement`

- CHANGELOG.md
- src/aux-common/bots/BotEvents.ts
- src/aux-runtime/runtime/AuxLibrary.spec.ts
- src/aux-runtime/runtime/AuxLibrary.ts
- src/aux-runtime/runtime/AuxLibraryDefinitions.def
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
-   Added the `os.capturePortalScreenshot()` function.
-   This function can be used to get a screenshot of the gridPortal.
Closes #464
> Implement `os.capturePortalScreenshot()`

- CHANGELOG.md
- policies/default/privacy-policy.md
- src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
- src/aux-server/aux-web/aux-auth/site/AuthApp/AuthApp.ts
- src/aux-server/aux-web/aux-auth/site/AuthApp/AuthApp.vue
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
- src/aux-server/aux-web/shared/vue-components/EnterAccountInfoDialog/EnterAccountInfoDialog.ts
- src/aux-server/aux-web/shared/vue-components/EnterAccountInfoDialog/EnterAccountInfoDialog.vue
- src/aux-server/aux-web/shared/vue-components/EnterAddressDialog/EnterAddressDialog.ts
- src/aux-server/aux-web/shared/vue-components/EnterAddressDialog/EnterAddressDialog.vue
- src/aux-server/aux-web/shared/vue-components/HasAccountDialog/HasAccountDialog.ts
- src/aux-server/aux-web/shared/vue-components/HasAccountDialog/HasAccountDialog.vue
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
- src/aux-vm/auth/AuxAuth.ts
-   [Casual Simulation is now PRIVO Certified!](https://cert.privo.com/#/companies/casualsimulation)
-   The certification seal has been added in various locations to notify users that Casual Simulation, ab1.bot, and publicos.link are [COPPA Safe Harbor Certified](https://www.ftc.gov/enforcement/coppa-safe-harbor-program).
Closes #482
> Add the PRIVO Certification Seal

- CHANGELOG.md
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/websockets/MemoryTempInstRecordsStore.ts
- src/aux-records/websockets/SplitInstRecordsStore.spec.ts
- src/aux-records/websockets/SplitInstRecordsStore.ts
- src/aux-records/websockets/TemporaryInstRecordsStore.ts
- src/aux-records/websockets/WebsocketController.spec.ts
- src/aux-records/websockets/WebsocketController.ts
- src/aux-server/aux-backend/prisma/PrismaAuthStore.ts
- src/aux-server/aux-backend/redis/RedisLock.ts
- src/aux-server/aux-backend/redis/RedisTempInstRecordsStore.ts
- src/aux-server/aux-backend/redis/RedisWebsocketConnectionStore.ts
- src/aux-server/aux-backend/schemas/migrations/20240701192238_make_oid_expires_at_ms_a_bigint/migration.sql
- src/aux-server/aux-backend/serverless/aws/src/handlers/Records.ts
- src/aux-server/aux-backend/serverless/aws/template.yml
-   Fixed an issue where different instances of the CasualOS server could try to save an inst at the same time and cause the inst to lose track of its data.
-   Fixed an issue where CasualOS would always decide to load inst data from Redis instead of the database.
-   Improved the CasualOS server to discard redundant updates when saving a studio inst. This will greatly help prevent hitting inst size limits in the future.
Fixes #498
> Improve private insts

- CHANGELOG.md
- src/aux-server/aux-web/aux-player/scene/PlayerPageSimulation3D.ts
- src/aux-server/aux-web/shared/scene/xr/WebXRControllerMesh.ts
-   Fixed an issue where meshes for hands in XR don't follow the camera when `cameraPositionOffset` is changed.
-   Fixed an issue where the wrist portals for hands in Meta Quest devices were positioned incorrectly.
Fixes #461
> Fix hand mesh positioning in XR

- CHANGELOG.md
- docs/docs/tags/portal-bot.mdx
- src/aux-server/aux-web/aux-player/scene/PlayerGame.ts
- src/aux-server/aux-web/shared/interaction/CameraControls.ts
- src/aux-server/aux-web/shared/scene/CameraRigFactory.ts
-   Improved `portalZoomableMax` and `portalZoomableMin` to be supported for `perspective` portal camera types.
Closes #459
> Add zoom limits for perspective cameras

- CHANGELOG.md
- src/aux-common/common/PolicyPermissions.ts
- src/aux-records/AIController.spec.ts
- src/aux-records/AIController.ts
- src/aux-records/AIHumeInterface.ts
- src/aux-records/MemoryStore.ts
- src/aux-records/PolicyController.spec.ts
- src/aux-records/RecordsController.spec.ts
- src/aux-records/RecordsController.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-records/RecordsStore.ts
- src/aux-records/SubscriptionConfiguration.ts
- src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
- src/aux-runtime/runtime/AuxLibrary.spec.ts
- src/aux-runtime/runtime/AuxLibrary.ts
- src/aux-runtime/runtime/RecordsEvents.ts
- src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
- src/aux-server/aux-backend/prisma/PrismaRecordsStore.ts
- src/aux-server/aux-backend/schemas/auth.prisma
- src/aux-server/aux-backend/schemas/migrations/20240715154333_add_hume_config_to_studio/migration.sql
- src/aux-server/aux-backend/shared/ServerBuilder.ts
- src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.ts
- src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.vue
- src/aux-vm/managers/RecordsManager.spec.ts
- src/aux-vm/managers/RecordsManager.ts
-   Improved Hume AI features to support Studios.
-   The `ai.hume` features now determine whether a Studio can configure their own Hume `apiKey` and `secretKey`.
-   `ai.hume.getAccessToken(recordName)` now accepts a record name.
-   This allows the user to specify which record they want to use for hume.ai access.
-   Once a studio is configured, requests to one of the Studio's records will return an access token derived from the Studio's configured `apiKey` and `secretKey`.
-   Requesting users require access to the `ai.hume` resource kind and `create` action for the specified record.
Closes #493
> Allow Studios to configure their own Hume API Key and Secret Key

- CHANGELOG.md
- src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
- src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
- src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.ts
- src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.vue
- src/aux-vm-browser/managers/AuthCoordinator.ts
- src/aux-vm-browser/managers/AuthEndpointHelper.ts
- src/aux-vm/auth/AuxAuth.ts
-   Updated the BIOS dialog with various visual improvements.
-   The default BIOS options have been updated:
-   `enter join code`
-   `local`
-   `studio`
-   `free`
-   `sign in`
-   `sign up`
-   `sign out`
-   Fixed an issue where selecting an option in the BIOS would fail to actually show the selected option.
Closes #505
> Update the BIOS Dialog

- CHANGELOG.md
- docs/docs/components.jsx
- docs/docs/tags/visualization.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/scene/Text3D.ts
- src/aux-server/aux-web/shared/scene/WordBubble3D.ts
- src/aux-server/aux-web/shared/scene/decorators/LabelDecorator.ts
- src/aux-server/aux-web/shared/scene/decorators/WordBubbleDecorator.ts
-   Added the `floatingBillboard` option for `labelPosition`.
-   Like `floating`, but the label background won't have an arrow and the label will always face the camera.
-   Added the `labelFloatingBackgroundColor` tag to control the color of the background for floating labels.
-   Defaults to `white`.
-   Fixed an issue where the arrow on floating labels would clip into the bot if the bot had a scale > 1.
Closes #503
> Improve labels

- CHANGELOG.md
- docs/docs/tags/listen.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue
- src/aux-server/aux-web/aux-player/MenuPortalConfig.ts
- src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerBotClickOperation.ts
- src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerEmptyClickOperation.ts
- src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
- src/aux-server/aux-web/shared/MonacoHelpers.ts
- src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseClickOperation.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/BaseEmptyClickOperation.ts
- src/aux-server/aux-web/shared/interaction/ClickOperation/ClickOperationUtils.ts
- src/aux-server/aux-web/shared/scene/Input.ts
- src/aux-server/aux-web/shared/vue-components/BotSheet/BotSheet.ts
- src/aux-server/aux-web/shared/vue-components/CodeToolsPortal/CodeToolsPortal.ts
- src/aux-server/aux-web/shared/vue-components/IdePortal/IdePortal.ts
- src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.ts
- src/aux-server/aux-web/shared/vue-components/TagPortal/TagPortalConfig.ts
-   Improved `@onClick`, `@onAnyBotClicked`, `@onGridClick`, `@onPointerEnter`, `@onPointerExit`, `@onPointerDown`, `@onPointerUp`, `@onAnyBotPointerEnter`, `@onAnyBotPointerExit`, `@onAnyBotPointerDown`, and `@onAnyBotPointerUp` to include the ID of the button that was pressed.
-   For each of these listeners, `that.buttonId` will be either `"left"`, `"right"`, `"middle"`, or `null`.
-   This means that you can now determine which button was pressed (if any) and respond accordingly.
Closes #492
> Add the ability to respond to right-click and middle-click in listeners

- CHANGELOG.md
- docs/docs/tags/visualization.mdx
- src/aux-common/bots/Bot.ts
- src/aux-common/bots/BotCalculations.ts
- src/aux-common/bots/test/BotCalculationContextTests.ts
- src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
-   Added the `meshPositioningMode` tag to prevent CasualOS from repositioning meshes around the center of the bot.
-   There are two possible values:
-   `center` - The mesh will be positioned so it is centered around the bot's center. (Default)
-   `absolute` - The mesh won't be repositioned. It will retain the position configured in the GLTF.
Closes #321
> Add the `#meshPositioningMode` tag

- CHANGELOG.md
- src/aux-server/aux-web/shared/scene/Arrow3D.ts
-   Fixed an issue where lines wouldn't draw to the center of the target bot when the bot was smaller than the arrow head length.
Fixes #460
> Fix line distance rendering when no arrow head is visible

- src/aux-records/websockets/MemoryLockStore.ts
- src/aux-records/websockets/MemoryTempInstRecordsStore.ts
- src/aux-records/websockets/TemporaryInstRecordsStore.ts
- src/aux-records/websockets/WebsocketController.spec.ts
- src/aux-records/websockets/WebsocketController.ts
- src/aux-server/aux-backend/redis/RedisLock.ts
- src/aux-server/aux-backend/redis/RedisTempInstRecordsStore.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
- src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
- src/aux-server/aux-web/shared/public/vue-qrcode-reader/src/components/QrcodeStream.ts
Refactored the implementation of acquireLock from within another store, to its own dedicated abstraction. Updated the implementing entities to match the new abstraction. Also fixed a typo in various locations aquire -> acquire.
> Refactor locking system to dedicated abstraction MemoryLockStore

- docker/docker-compose.dev.yml
This commit updates the docker-compose.dev.yml file to enable IPv6 networking. 
It adds a new network "enable_ipv6", as a bridge.
This network assigns IPv4 and IPv6 subnets. 
All previously declared services, now use this network.
The redis container now is instructed to bind ipv4 to ipv6.
This solves a connection issue present when the host alias "localhost" (used frequently within the source) resolves to its ipv6 address rather than ipv4.
> refactor: Update docker-compose.dev.yml to enable IPv6 networking

- src/aux-common/bots/BotCalculations.ts
- src/aux-runtime/runtime/AuxCompiler.ts
- src/aux-runtime/runtime/Transpiler.spec.ts
- src/aux-runtime/runtime/Transpiler.ts
Fixes #569. AuxCompiler will now ignore nested content when checking if a script tag should be treated as asynchronous.
> Remove content of curly brackets (functions) before checking if a script tag should be considered async

- CHANGELOG.md
- src/aux-vm-browser/managers/LivekitManager.ts
> Fix/joining room using os.join room() fails if casual os does not have permission to camera or mic

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/release.yml
- CHANGELOG.md
- src/aux-server/aux-web/shared/MediaUtils.ts
- src/aux-server/aux-web/shared/UrlUtils.spec.ts
- src/aux-server/aux-web/shared/UrlUtils.ts
- src/aux-server/aux-web/shared/scene/AuxTextureLoader.ts
- src/aux-server/aux-web/shared/scene/Game.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.spec.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/vue-components/HtmlApp/HtmlApp.ts
-   Added the ability to use CasualOS URLs in `<video>` HTML custom app elements.
-   This makes it possible to use LiveKit tracks in a custom app.
-   Tip: Utilize the `autoplay` attribute to automatically play video from a track.
> (v.3.1.37) Add the ability to use livekit tracks in custom apps

- CHANGELOG.md
- src/aux-server/aux-web/shared/MediaUtils.ts
- src/aux-server/aux-web/shared/UrlUtils.spec.ts
- src/aux-server/aux-web/shared/UrlUtils.ts
- src/aux-server/aux-web/shared/scene/AuxTextureLoader.ts
- src/aux-server/aux-web/shared/scene/Game.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.spec.ts
- src/aux-server/aux-web/shared/scene/SceneUtils.ts
- src/aux-server/aux-web/shared/vue-components/HtmlApp/HtmlApp.ts
-   Added the ability to use CasualOS URLs in `<video>` HTML custom app elements.
-   This makes it possible to use LiveKit tracks in a custom app.
-   Tip: Utilize the `autoplay` attribute to automatically play video from a track.
Closes #575
> Add the ability to use livekit tracks in custom apps

- docs/docs/tags/listen.mdx
- docs/versioned_docs/version-3.1.36/listen-tags.mdx
Should have been `os.enableVR(options?)`
> Fixed typo in docs referencing 'os.enterVR'

- CHANGELOG.md
- src/aux-records/AuthController.spec.ts
- src/aux-records/MemoryStore.ts
- src/aux-records/PolicyController.spec.ts
- src/aux-records/PrivoClient.ts
- src/aux-records/RecordsController.spec.ts
- src/aux-records/RecordsController.ts
- src/aux-records/RecordsServer.spec.ts
- src/aux-records/RecordsServer.ts
- src/aux-records/RecordsStore.ts
- src/aux-records/TestUtils.ts
- src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
- src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
- src/aux-server/aux-backend/prisma/PrismaRecordsStore.ts
- src/aux-server/aux-backend/shared/ServerBuilder.ts
- src/aux-server/aux-web/aux-auth/shared/AuthManager.ts
- src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.ts
- src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.vue
-   Improved studios to support adding Privo users by email, display name, or user ID.
-   Additionally improved studios to only show members by name and display name when Privo support is enabled.
Closes #554
> Support adding Privo users by email, display name, or user ID

- CHANGELOG.md
- src/aux-records/OpenAIChatInterface.ts
- src/aux-records/ServerConfig.spec.ts
- src/aux-records/ServerConfig.ts
- src/aux-records/__snapshots__/ServerConfig.spec.ts.snap
- src/aux-server/aux-backend/shared/ServerBuilder.ts
- src/aux-server/aux-web/shared/vue-components/BaseGameView.ts
-   Added the ability to configure CasualOS to use a custom [OpenAI Completions API-compatible](https://platform.openai.com/docs/api-reference/completions) integration for the `ai.chat()` API for a set of models.
-   To configure, provide an allowed model that sets `provider` to `custom-openai-completions` and also has the following list of properties:
-   `name` The name that should be used for this provider in the logs.
-   `apiKey` - The API Key that should be used for requests to this provider.
-   `baseUrl` - The URL that requests should be made to. (e.g. "https://api.openai.com/v1/" for OpenAIs API)
-   `models` - The array of models that should use this provider.
-   Here's an example:
```json
{
"provider": "custom-openai-completions",
"name": "custom",
"apiKey": "my-api-key", …
```
> Add support for custom AI Chat integrations which are compatible with the OpenAI Completions API

- CHANGELOG.md
- docs/docs/components.jsx
- docs/docs/tags/config-bot.mdx
- docs/docs/tags/visualization.mdx
- src/aux-common/bots/Bot.ts
- src/aux-server/aux-backend/shared/ServerBuilder.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.css
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
- src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue
-   Added the `formInputMultiline` tag.
-   Set to `true` to allow multiple lines in `input` form menu bots.
-   Set to `false` to disallow multiple lines.
-   Set to `null` to allow multiple lines by using <kbd>Shift</kbd>+<kbd>Enter</kbd>.
Closes #617
> Add support for multiline input in menu bots

- src/casualos-cli/cli.ts
```bash
casualos aux [options] [action]   #Work with aux files and their contents.
```
The aux command contains an **action argument** and an option (**-ls**, **--list**).
The aforementioned `-ls`/`--list` option will list all possible values for it's argument: `action`.
Currently the only **action argument** is `convert` which will effectively proxy the provided `.aux` file(s) through [**@casual-simulation/aux-common**](https://www.npmjs.com/package/@casual-simulation/aux-common)'s `getBotsStateFromStoredAux` function; subsequently outputting the result to file(s) nominally the same in the specified output directory.
The naming convention has one exemption, that is, when the target file directory and output directory are the same. To avoid overwriting, the output file will be prefixed …
> Add aux tools to casualos cli

- CHANGELOG.md
- src/aux-vm/managers/RecordsManager.spec.ts
- src/aux-vm/managers/RecordsManager.ts
-   Changed local insts (`?staticInst` in the URL query) to no longer require separate permission for performing records actions.
-   Previously, public (sometimes called free) insts and local insts had to be granted separate permission for actions that manipulated data.
-   This led to a large number of uses of `os.grantInstAdminPermission()`, which was a workaround to allow people to grant an inst permissions.
-   The goal was to replace this mechanism by encouraging switching to packages and entitlements which are able to automatically grant insts permissions based on the entitlement grants that users have given indiviaual packages.
-   Unfortunately, packages aren't a good solution for scenarios when actively developing AUXes and (as a result) developers are forced to continue using …
> Change local insts to not require separate permissions
